{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "KS-SQL2018;Reporting_ASSS",
        "connectionString": "Provider=SQLNCLI11;Data Source=KS-SQL2018;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=Reporting_ASSS",
        "impersonationMode": "impersonateAccount",
        "account": "KSINT\\8093AHA",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Art",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Art].* FROM [dbo].[Art] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Art].* FROM [dbo].[Art] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Art"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "ASSS Indikatorer",
        "isHidden": true,
        "columns": [
          {
            "name": "Barnehage",
            "dataType": "int64",
            "sourceColumn": "Barnehage",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Miljøforvaltning",
            "dataType": "int64",
            "sourceColumn": "Miljøforvaltning",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Samferdsel",
            "dataType": "int64",
            "sourceColumn": "Samferdsel",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Barnevern",
            "dataType": "int64",
            "sourceColumn": "Barnevern"
          },
          {
            "name": "Pleie og omsorg",
            "dataType": "int64",
            "sourceColumn": "Pleie og omsorg"
          },
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Byggesak",
            "dataType": "int64",
            "sourceColumn": "Byggesak"
          },
          {
            "name": "Eiendomsforvaltning",
            "dataType": "int64",
            "sourceColumn": "Eiendomsforvaltning"
          },
          {
            "name": "Kommunehelse",
            "dataType": "int64",
            "sourceColumn": "Kommunehelse"
          },
          {
            "name": "Sosiale tjenester",
            "dataType": "int64",
            "sourceColumn": "Sosiale tjenester"
          }
        ],
        "partitions": [
          {
            "name": "ASSS Indikatorer",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>149</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>184</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>147</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "SFS Kommunale veier i km per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "",
              "var lengde_komvei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(lengde_komvei, DIVIDE(innb, 10000)),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Antall km tilrettelagt for syklende som kommunen har ansvaret for per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var lengde_syklende = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde  tilrettelagt for syklende som kommunen har ansvaret for (km)\")",
              ")",
              "",
              "var innb_ant = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(lengde_syklende, DIVIDE(innb_ant, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Brutto driftsutgifter eksklusiv avskrivninger samferdsel per km (kroner)",
            "expression": [
              " ",
              "",
              "var agd10 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"332\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")   ",
              "",
              "var a590 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),  ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A590\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"332\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ") ",
              "",
              "var vei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "Return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (agd10 - a590) * 1000, ",
              "            vei",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnader til gatebelysning per lyspunkt, kommunale veier",
            "expression": [
              "",
              "var gate = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12183\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutgifter til gatebelysning langs kommunale veier og gater (1000 kr)\")",
              ")   ",
              "",
              "var lys = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11845\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lyspunkt langs kommunale veier og gater (antall)\")   ",
              ")  ",
              "",
              "RETURN (",
              "    ROUND(",
              "        DIVIDE((gate * 1000), lys),",
              "        1  ",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Drenering/overvann, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutg eks avskrivninger til drenering/overvann\"",
              "    )",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Trafikksikkerhet inkludert skilting og veimerking, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutg eks avskrivninger til trafikksikkerhet inkl skilting og vegmerking\"",
              "    )",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Renhold, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til renhold\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Vinterdrift, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til vinterdrift\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Investeringer til veidekker (asfalt) per meter vei (kroner)",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Investeringer til veidekker\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde * 1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Sykefravær samferdsel (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Samferdsel (PAI)\")",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Veidekker, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til veidekker\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutto, lengde*1000),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel adkomst- og GS-vei på og/eller over akseptabel standard - tilstandsgrad TG2 (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Andel adkomst- og GS-veg over akseptabelt nivå > TG2\")",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel gate og samlevei på og/eller over akseptabel standard - tilstandsgrad TG1 (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Andel gate og samleveg over akseptabelt nivå > TG1\")",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnad per meter vei for å komme over akseptabel standard (kroner)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Kostnad per meter veg for å komme over akseptabel standard\"",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "BNV Netto driftsutgifter barnevernstjenester per innbygger 0-17 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] IN {\"244\", \"251\", \"252\"}),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE((ndrbv*1000), barn),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel barn med undersøkelser i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "/* gammel kode",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Barn med undersøking  (antall)\");",
              "(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100",
              "*/",
              "",
              "var barn_und =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12286\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med undersøking  (antall)\")",
              ")",
              "",
              "var pers_017 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barn_und, pers_017) * 100,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel barn med barneverntiltak i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "/*",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\");",
              "(CALCULATE(sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100",
              "*/",
              "",
              "",
              "/* Valg mellom i løpet av året eller per 31.12 */",
              "var barn_mtiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-22 år\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonsnavn]), [Dimensjonsnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "var pers_017 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL('Alder'[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(    ",
              "        DIVIDE(barn_mtiltak, pers_017) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)",
            "expression": [
              "",
              "/*",
              "CALCULATE(SUM('Alle Data'[Verdi]);",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "    FILTER(ALL(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))",
              "*/",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Funksjon[Dimensjonsnavn]), [Dimensjonsnavn] = ",
              "        \"252 - Barnevernstiltak når barnet er plassert av barnevernet\"",
              "    ),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0-22 år\")",
              ")"
            ]
          },
          {
            "name": "BNV Andel barn som er plassert i løpet av året i prosent av antall barn 0-17 år",
            "expression": [
              "",
              "",
              "var barn_017 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)], ",
              "            barn_017",
              "        ) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)",
            "expression": [
              "",
              "/*",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Funksjon'[Dimensjonskode]);'Funksjon'[Dimensjonskode] = \"251\");",
              "FILTER(ALL(Variabel[Variabelnavn]); ",
              "Variabel[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Funksjon[Dimensjonsnavn]), Funksjon[Dimensjonsnavn] = ",
              "        \"251 - Barnevernstiltak når barnet ikke er plassert av barnevernet\"",
              "    ),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\")",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel barn som ikke er plassert i løpet av året i prosent av alle i tiltak  (0-22 år)",
            "expression": [
              "",
              "/*",
              "var tiltak022 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); ",
              "'Variabel'[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\")",
              ")",
              "",
              "return DIVIDE([Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)];tiltak022)*100",
              "*/",
              "",
              "var tiltak022 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL(Funksjon[Dimensjonsnavn]), [Dimensjonsnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)],",
              "            tiltak022",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f251) som ikke er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD10\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"251\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return DIVIDE((brbv*1000);[Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)])",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"251\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              " )",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            brbv * 1000, ",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)]",
              "        ),",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD10\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000); [Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              " )",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            brbv * 1000,",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f244) med undersøkelse eller tiltak (kroner)*",
            "expression": [
              "",
              "/*",
              "var br244 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12279\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Brutto driftsutgifter (funksjon 244) per barn med undersøking eller tiltak (kr)\")",
              ")",
              "",
              "return br244",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12279\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutgifter (funksjon 244) per barn med undersøking eller tiltak (kr)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel undersøkelser gjennomført i løpet av 3 måneder (prosent)*",
            "expression": [
              "",
              "/*",
              "var und= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12280\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Undersøkingar med handsamingstid innan 3 månader (prosent)\")",
              ")",
              "",
              "return und",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12280\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Undersøkingar med handsamingstid innan 3 månader (prosent)\"",
              "    )",
              ")"
            ]
          },
          {
            "name": "BNV Sykefravær barnevern (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"PAI02\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Barnevern (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Barnevern (PAI)\")",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Netto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000);[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            brbv * 1000,",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              "        ),",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f244 (prosent)",
            "expression": [
              "",
              "/*",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"FGK13\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto244 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"244\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto244;nettobv))*100",
              "*/",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto244 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"244\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto244, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f251 (prosent)",
            "expression": [
              "",
              "/*",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"FGK13\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto251 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"251\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto251;nettobv))*100",
              "*/",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto251 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"251\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto251, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f252 (prosent)",
            "expression": [
              "",
              "",
              "/*",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"FGK13\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto252 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Art'[Dimensjonskode]); [Dimensjonskode] = \"AGD2\");",
              "FILTER(ALL('Funksjon'[Dimensjonskode]); [Dimensjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto252;nettobv))*100",
              "*/",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto252 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto252, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel barn med melding av innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "/*",
              "var melding = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12615\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(ALL('Alle Data'[Tabell]);'Alle Data'[Tabell]=\"11805\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return (divide(melding;barn))*100",
              "*/",
              "var melding = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12615\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] =  \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(melding, barn) * 100,",
              "        1",
              "    )",
              ")",
              "    ",
              ""
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Antall barn med undersøkelse eller tiltak per årsverk (funksjon 244)*",
            "expression": [
              "",
              "/*",
              "var barn = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12280\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\")",
              ")",
              "",
              "return barn",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12280\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\"",
              "    )",
              ")"
            ]
          },
          {
            "name": "BNV Stillinger med fagutdanning av alle fag- og tiltaksstillinger (prosent)",
            "expression": [
              "",
              "/*",
              "var fag = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12305\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Stillingar med fagutdanning (årsverk)\")",
              ")",
              "",
              "var stillinger= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(ALL('Alle Data'[Tabell]);'Alle Data'[Tabell]=\"12305\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\")",
              ")",
              "",
              "return (divide(fag;stillinger)*100)",
              "*/",
              "var fag = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12305\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Stillingar med fagutdanning (årsverk)\")",
              ")",
              "",
              "var stillinger = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12305\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(fag, stillinger) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel meldinger som går til undersøkelser (prosent)",
            "expression": [
              "",
              "/*",
              "var und = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12189\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Til undersøkelse Meldinger i alt\")",
              ")",
              "",
              "var meld= CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(ALL('Alle Data'[Tabell]);'Alle Data'[Tabell]=\"12189\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Meldinger i alt Meldinger i alt\")",
              ")",
              "",
              "return (divide(und;meld)*100)",
              "*/",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12189\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Meldingar til barnevernet (antall)\"),",
              "    FILTER(ALL(Konklusjon[Dimensjonsnavn]), [Dimensjonsnavn] = \"Til undersøkelse\"),",
              "    FILTER(ALL(Handsamingstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Meldinger i alt\")",
              ")",
              "",
              "var meld = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12189\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Meldingar til barnevernet (antall)\"),",
              "    FILTER(ALL(Handsamingstid[Dimensjonsnavn]), [Dimensjonsnavn] = \"Meldinger i alt\"),",
              "    FILTER(ALL(Konklusjon[Dimensjonsnavn]), [Dimensjonsnavn] = \"Meldinger i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, meld) * 100,",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "BVN Brutto driftsutgifter per EM (f252) (kroner)",
            "expression": [
              "",
              "/*",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "return divide((brem*1000);antall)",
              "*/",
              "",
              "var brem = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] =",
              "        \"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\"",
              "    )",
              ")",
              "",
              "var antall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brem * 1000, antall),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "PLO Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 0 til 66 år",
            "expression": [
              "",
              "/*",
              "var behov1 = ",
              "CALCULATE(sum('Alle Data'[Verdi]);",
              "    FILTER(ALL(Tabeller[Tabellnummer]); [Tabellnummer] = \"12292\");",
              "    filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 0-66 år (antall)\")",
              ")",
              "",
              "var behov2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, middels bistandsbehov, 0-66 år (antall)\")",
              ")",
              "",
              "var behov3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere,  omfattende bistandsbehov,  0-66 år (antall)\")",
              ")",
              "",
              "return divide(((behov1*1)+(behov2*2)+(behov3*3));(behov1+behov2+behov3))",
              "*/",
              "var behov1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var behov2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, middels bistandsbehov, 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var behov3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere,  omfattende bistandsbehov,  0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (behov1 * 1) + (behov2 * 2) + (behov3 * 3),",
              "            behov1 + behov2 + behov3",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 67 år+",
            "expression": [
              "",
              "/*",
              "var behov1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "var behov2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, middels bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "var behov3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Hjemmetjenestebrukere, omfattende bistandsbehov, 67 år og over (antall)\")",
              ")",
              "",
              "return divide(((behov1*1)+(behov2*2)+(behov3*3));(behov1+behov2+behov3))",
              "*/",
              "var behov1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var behov2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, middels bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var behov3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, omfattende bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (behov1 * 1) + (behov2 * 2) + (behov3 * 3),",
              "            behov1 + behov2 + behov3  ",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere i institusjon som har omfattende bistandsbehov: Langtidsopphold (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Institusjon - beboere på langtidsopphold, omfattende bistandsbehov (antall)\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Institusjon - beboere på langtidsopphold (antall)\")))*100",
              "*/",
              "var beb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - beboere på langtidsopphold (antall)\")",
              ")",
              "",
              "",
              "var bebomf = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Institusjon - beboere på langtidsopphold, omfattende bistandsbehov (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(bebomf, beb) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel timer hjemmetjeneste brukere 0-66 år",
            "expression": [
              "",
              "/*",
              "var timer1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\")",
              ")",
              "var brukere1= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var timer2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\")",
              ")",
              "var brukere2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\"; \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((timer1*brukere1*52);(timer1*brukere1*52+brukere2*timer2*52))*100",
              "*/",
              "var timer1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\"",
              "    )",
              ")",
              "var brukere1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var timer2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\"",
              "    )",
              ")",
              "var brukere2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"67-79 år\",",
              "        \"over 80 år\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "return (",
              "    ",
              "    ROUND(",
              "        DIVIDE(",
              "            timer1 * brukere1,",
              "            timer1 * brukere1 + brukere2 * timer2",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel timer hjemmetjeneste brukere 67 år +",
            "expression": [
              "",
              "/*",
              "var timer1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\")",
              ")",
              "var brukere1= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var timer2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\")",
              ")",
              "var brukere2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\"; \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((timer2*brukere2*52);(timer1*brukere1*52+brukere2*timer2*52))*100",
              "*/",
              "var timer1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\"",
              "    )",
              ")",
              "var brukere1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var timer2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\"",
              "    )",
              ")",
              "var brukere2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"67-79 år\",",
              "        \"over 80 år\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            timer2 * brukere2,",
              "            timer1 * brukere1 + brukere2 * timer2",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 0-66 år per innbygger 0-66 år (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0 - 66 år\")",
              ")",
              "",
              "return Divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 0-66 år]/100)*1000);bef)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 0-66 år], 100) * 1000,",
              "            bef",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 67 + år per innbygger 67 år+ (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"})",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) over 67 år\")",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 67 år +]/100)*1000);bef)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 67 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 67 år +], 100) * 1000,",
              "            bef",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 0-66 år som er beboere på institusjon eller mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "/*",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "var gr2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Institusjonstenester\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) 0 - 66 år\")",
              ")",
              "",
              "return divide((gr1+gr2);bef)*100",
              "*/",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Institusjonstenester\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(gr1 + gr2, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 80 år og eldre som mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Brukere (antall) over 80 år Heimeteneste\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Personer (antall) over 80 år\")))*100",
              "*/",
              "",
              "var br80he = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 80 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "var pe80 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 80 år\")",
              ")",
              " ",
              "return (",
              "    ROUND(",
              "        DIVIDE(br80he, pe80) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 80 år+ beboer på institusjon eller i bolig med heldøgns bemanning(prosent)",
            "expression": [
              "",
              "/*",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Beboere bolig m/ fast tilknyttet bemanning hele døgnet 80 år og over (antall)\")",
              ")",
              "",
              "var gr2= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]=\"Institusjon - beboere 80 år og over (antall)\")",
              ")",
              "",
              "var bef = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11805\"); ",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Personer (antall) over 80 år\")",
              ")",
              "",
              "return divide((gr1+gr2);bef)*100",
              "*/",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beboere bolig m/ fast tilknyttet bemanning hele døgnet 80 år og over (antall)\")",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - beboere 80 år og over (antall)\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] =\"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"over 80 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(gr1 + gr2, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere på institusjon 0-66 år (prosent)",
            "expression": [
              "",
              "/*",
              "Divide(CALCULATE(Sum('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Brukere (antall) 0 - 66 år Institusjonstenester\");",
              "(CALCULATE(SUM('Alle Data'[Verdi]);Variabel[Variabelnavn]=\"Brukere (antall) I alt Institusjonstenester\")))*100",
              "*/",
              "var br066inst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Institusjonstenester\")",
              ")",
              "",
              "var braltinst = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"I alt\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Institusjonstenester\")",
              ")",
              "",
              "return (",
              "   ROUND(",
              "        DIVIDE(br066inst, braltinst) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Brutto driftsutgifter per plass i institusjon (kroner)",
            "expression": [
              "",
              "/*",
              "var brutg = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(ALL('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"253\"; \"261\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var plasser = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11875\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Institusjon - alle disponible plasser (antall)\")",
              ")",
              "",
              "return divide((brutg*1000);plasser)",
              "*/",
              "var brutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] IN {",
              "        \"253\", ",
              "        \"261\"",
              "    }),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var plasser = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11875\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - alle disponible plasser (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutg * 1000, plasser),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 0-66 år per mottaker 0-66 år (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12003\");",
              "FILTER(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Brukere (antall) 0 - 66 år Heimeteneste\")",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 0-66 år]/100)*1000);mott066)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 0-66 år], 100) * 1000,",
              "            mott066",
              "        ),",
              "        0",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 67 + år per mottaker 67 år+ (kroner)",
            "expression": [
              "",
              "/*",
              "var netto066 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "filter(all('Artsgruppe Kostra'[Artsgruppekode]); 'Artsgruppe Kostra'[Artsgruppekode]=\"AGD2\");",
              "filter(all('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] in {\"254\"});",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott67= CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell]=\"12003\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn]  in {\"Brukere (antall) 67-79 år Heimeteneste\"; \"Brukere (antall) over 80 år Heimeteneste\"})",
              ")",
              "",
              "return divide((netto066*('Nøkkeltall tjenester'[Andel timer hjemmetjeneste brukere 67 år +]/100)*1000);mott67)",
              "*/",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    filter(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "    filter(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"254\"),",
              "    filter(ALL('Variabel'[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var mott67= ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    filter(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"67-79 år\",",
              "        \"over 80 år\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Dimensjonsnavn]), [Dimensjonsnavn] = \"Heimeteneste\")",
              ")",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 67 år +], 100) * 1000,",
              "            mott67",
              "        ),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel årsverk i brukerrettede tjenester med fagutdanning (prosent)",
            "expression": [
              "",
              "/*",
              "var gr1 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12292\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] in {\"Årsverk i brukerrettede tjenester m/ helseutdanning fra videregående skole (antall)\"; ",
              "\"Årsverk i brukerrettede tjenester m/ helseutdanning fra høyskole/universitet (antall)\"})",
              ")",
              "",
              "var gr2 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11924\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] = \"Avtalte årsverk (årsverk) Omsorgstjenestene i alt\")",
              ")",
              "",
              "var gr3 = CALCULATE(sum('Alle Data'[Verdi]);",
              "FILTER(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"11924\");",
              "filter(all(Variabel[Variabelnavn]); Variabel[Variabelnavn] in {\"Avtalte årsverk (årsverk) Administrativt personell\"; \"Avtalte årsverk (årsverk) Servicefunksjon\"})",
              ")",
              "",
              "return divide(gr1;(gr2-gr3))*100",
              "*/",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "    \"Årsverk i brukerrettede tjenester m/ helseutdanning fra videregående skole (antall)\", ",
              "    \"Årsverk i brukerrettede tjenester m/ helseutdanning fra høyskole/universitet (antall)\"",
              "    })",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11924\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] = \"Omsorgstjenestene i alt\")",
              ")",
              "",
              "var gr3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11924\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Dimensjonsnavn]), [Dimensjonsnavn] IN {",
              "        \"Administrativt personell\",",
              "        \"Servicefunksjon\"",
              "    })",
              ")",
              "return (",
              "    ROUND(",
              "        DIVIDE(gr1, gr2-gr3) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Ressursbruksindikator. Pleie og omsorg*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Pleie og omsorg\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Sykefravær pleie og omsorg (PAI) (prosent)*",
            "expression": [
              "",
              "/*",
              "var a = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"ASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Sykefravær Pleie og omsorg (PAI)\")",
              ")",
              "",
              "return a",
              "*/",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"PAI02\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Pleie og omsorg (PAI)\")",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Legetimer per uke per beboer i sykehjem (timer)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12293\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Legetimer per uke per beboer i sykehjem (timer)\")",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel utviklingshemmede av befolkningen 16 år og eldre (TTU) (prosent)*",
            "expression": [
              "",
              "",
              "var utv16 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel utviklingshemmede av befolkningen 16 år og eldre (TTU) (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(utv16, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Utgifter per utviklingshemmet (fratrukket refusjon ressurskrevende) (TTU) (kroner)*",
            "expression": [
              "",
              "",
              "var utgutv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter per utviklingshemmet (fratrukket refusjon ressurskrevende) (TTU) (kroner)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(utgutv, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel utviklingshemmede 18 år+ i bolig med fast tilknyttet personell hele døgnet (TTU)(prosent)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel utviklingshemmede 18 år og eldre som bor i bolig med fast tilknyttet personell hele døgnet (TTU) (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Utgifter bolig med fast personell hele døgnet (inkl. private/ideelle) per beboer (TTU) (kroner)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter til bolig med fast tilknyttet personell hele døgnet (inkl. private/ideelle) per beboer (TTU) (kroner)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel årsverk med fagutdanning (TTU) (prosent)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel årsverk med fagutdanning (TTU) (prosent)\")",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "BVN Brutto driftsutgifter per plassert barn uten EM (f252) (kroner)",
            "expression": [
              "",
              "/*",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"12367\");",
              "FILTER(ALL('Artsgruppe Kostra'[Artsgruppekode]);'Artsgruppe Kostra'[Artsgruppekode] = \"AGD10\");",
              "FILTER(ALL('Funksjon Kostra'[Funksjonskode]); 'Funksjon Kostra'[Funksjonskode] = \"252\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return DIVIDE(((brbv-brem)*1000);",
              "('Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]-antall))",
              "*/",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "    FILTER(ALL(Art[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var brem = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\"",
              "    )",
              ")",
              "",
              "var antall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Antall enslige mindreårige f252\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            (brbv - brem) * 1000, ",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)] - antall",
              "        ),",
              "        1",
              "    )",
              ")"
            ]
          },
          {
            "name": "BVN Andel EM av alle plasserte barn (prosent)",
            "expression": [
              "",
              "/*",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "",
              "return (DIVIDE(antall;('Nøkkeltall tjenester'[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]))*100)",
              "*/",
              "var antall =",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    filter(all(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "        \"Antall enslige mindreårige f252\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(",
              "            antall,",
              "            [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              "        ) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Andel barn med tiltak 0-5 år av barn på tiltak 0-17 år (prosent)",
            "expression": [
              "",
              "/*",
              "var antall1 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn]=",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\")",
              ")",
              "var antall2 = CALCULATE(SUM('Alle Data'[Verdi]);   ",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"BMT\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] in ",
              "{\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\";",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 6-12 år\";",
              "\"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 13-17 år\"})",
              ")",
              "",
              "return (DIVIDE(antall1;antall2)*100)",
              "*/",
              "var antall1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] =",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\"",
              "    )",
              ")",
              "",
              "var antall2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] IN {",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 0-5 år\",",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 6-12 år\",",
              "        \"Barn med barnevernstiltak i løpet av året, etter aldersgrupper - 13-17 år\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(antall1, antall2) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BNV Ressursbruksindikator. Barnevern*",
            "expression": [
              "",
              "/*",
              "var r = CALCULATE(sum('Alle Data'[Verdi]);",
              "filter(all('Alle Data'[Tabell]); 'Alle Data'[Tabell] = \"RBIASSS\");",
              "filter(all('Variabel'[Variabelnavn]); 'Variabel'[Variabelnavn] = \"Ressursbruksindikator Barnevern\")",
              ")",
              "",
              "return r",
              "*/",
              "var rbi = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator Barnevern\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 1)",
              ")"
            ],
            "displayFolder": "Barnvern"
          },
          {
            "name": "BGS Sykefravær byggesak (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"PAI02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefravær Byggesak (PAI)\")",
              ")"
            ]
          },
          {
            "name": "Godkjente boligenheter per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12295\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Netto endring i antall boliger (antall)\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1,(var2/1000))",
              ""
            ]
          },
          {
            "name": "Godkjent annet areal per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"05939\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Fullført bruksareal til annet enn bolig\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1,(var2/1000))"
            ]
          },
          {
            "name": "Gjennomsnittlig saksbehandlingstid ett-trinnssøknader, 12-uker (dager)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12295\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig saksbehandlingstid for byggesaker med 12 ukers frist (dager)\")",
              ")",
              "",
              "return a"
            ]
          },
          {
            "name": "Saksbehandlingsgebyr for oppføring av enebolig (kroner)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12303\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Byggesaksgebyr for oppføring av enebolig (kr)\")",
              ")",
              "",
              "return a"
            ]
          },
          {
            "name": "Nye søknader per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ") ",
              "",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11805\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) I alt\") ",
              ")  ",
              "",
              "",
              "return divide(var1,(var2/1000))",
              ""
            ]
          },
          {
            "name": "Tilsyn i % av nye byggesaker",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12224\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Byggesaker med tilsyn (antall)\") ",
              ")  ",
              "var var1b = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12612\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Behandlete søknader om eierseksjonering (antall)\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12224\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Behandlede byggesøknader i alt (antall)\") ",
              ") ",
              "",
              "return (divide((var1+var1b),var2))*100",
              ""
            ]
          },
          {
            "name": "Antall utførte tilsyn med ikke omsøkt byggevirksomhet*",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11879\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Tilsyn i ikke omsøkte byggesaker (antall)\") ",
              ")  ",
              "",
              "return (var1)"
            ]
          },
          {
            "name": "Andel mangelfulle søknader i prosent av vedtak",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Antall mangelfulle søknader hvor det ble bedt om tilleggsdokumentasjon\") ",
              ")  ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return (divide(var1,var2))*100",
              ""
            ]
          },
          {
            "name": "Brutto driftsutgifter per ferdigbehandlet byggesak (f302) (kroner)",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12611\"),",
              "filter(all('Funksjon Kostra'[Funksjonskode]), 'Funksjon Kostra'[Funksjonskode] in {\"302\"}),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"2. Brutto driftsutgifter (1000 kr)\")",
              ")",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return ((divide(var1,var2))*1000)",
              ""
            ]
          },
          {
            "name": "Andel vedtak innenfor frist (prosent)",
            "expression": [
              "",
              " ",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader med saksbehandlingstid over lovpålagt tid\") ",
              ") ",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader mottatt av kommunen\") ",
              ")",
              "",
              "return (divide((var2-var1),var2))*100",
              ""
            ]
          },
          {
            "name": "Totale gebyrinntekter bygge- og delesaksbehandling per f.g.vedtak (kroner)",
            "expression": [
              "",
              "",
              "var var1 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12299\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Beløp (1000 kr) Bygge- og delesaksbehandling Gebyrinntekter\") ",
              ")  ",
              "",
              "var var1b = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12299\"), ",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Beløp (1000 kr) Eierseksjonering Gebyrinntekter\") ",
              ")  ",
              "",
              "var var2 = CALCULATE(sum('Alle Data'[Verdi]), ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11211\"), ",
              "filter(all('Variabel'[Variabelnavn]), Variabel[Variabelnavn] = \"Antall søknader kommunen behandlet ferdig (fattet vedtak om)\") ",
              ") ",
              "",
              "return (divide(((var1+var1b)*1000),var2))"
            ]
          },
          {
            "name": "Gjennomsnittlig stønadslengde med sosialhjelp som hovedinntekt (måneder)",
            "expression": [
              "",
              "",
              "var soslg = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\")",
              ")",
              "",
              "return soslg",
              "",
              "",
              ""
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ASSS Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>149</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>184</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <int>147</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Energitype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Energitype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Energitype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Funksjon",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Funksjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Region",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alle Data",
        "isHidden": true,
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Energitypekode",
            "dataType": "string",
            "sourceColumn": "Energitypekode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Handsamingstidkode",
            "dataType": "string",
            "sourceColumn": "Handsamingstidkode"
          },
          {
            "name": "Konklusjonkode",
            "dataType": "string",
            "sourceColumn": "Konklusjonkode"
          },
          {
            "name": "Tiltakskategorikode",
            "dataType": "string",
            "sourceColumn": "Tiltakskategorikode"
          },
          {
            "name": "Alderkode",
            "dataType": "string",
            "sourceColumn": "Alderkode"
          },
          {
            "name": "Kilde",
            "dataType": "string",
            "sourceColumn": "Kilde"
          },
          {
            "name": "Omsorgs-/hjelpetiltakkode",
            "dataType": "string",
            "sourceColumn": "Omsorgs-/hjelpetiltakkode"
          },
          {
            "name": "Tjenestegrupperkode",
            "dataType": "string",
            "sourceColumn": "Tjenestegrupperkode"
          },
          {
            "name": "Utdanningkode",
            "dataType": "string",
            "sourceColumn": "Utdanningkode"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>52</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>155</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>189</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilde</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilde</string>",
              "      </key>",
              "      <value>",
              "        <int>52</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>155</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>189</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilde</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilde</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Alder",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Alder",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alder"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Handsamingstid",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Handsamingstid",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Handsamingstid].* FROM [dbo].[Handsamingstid] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Handsamingstid].* FROM [dbo].[Handsamingstid] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Handsamingstid"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Kilde",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Kilde",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Kilde].* FROM [dbo].[Kilde] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kilde].* FROM [dbo].[Kilde] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kilde"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Konklusjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Konklusjon",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Konklusjon].* FROM [dbo].[Konklusjon] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Konklusjon].* FROM [dbo].[Konklusjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Konklusjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Omsorgs-hjelpetiltak",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Omsorgs-hjelpetiltak",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Omsorgs-/hjelpetiltak].* FROM [dbo].[Omsorgs-/hjelpetiltak] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Omsorgs-/hjelpetiltak].* FROM [dbo].[Omsorgs-/hjelpetiltak] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Omsorgs-/hjelpetiltak"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Sammenslåtte Regioner",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "SammenslåingsDato",
            "dataType": "dateTime",
            "sourceColumn": "SammenslåingsDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Sammenslåtte Regioner",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sammenslåtte Regioner"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tiltakskategori",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tiltakskategori",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tiltakskategori].* FROM [dbo].[Tiltakskategori] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tiltakskategori].* FROM [dbo].[Tiltakskategori] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tiltakskategori"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tjenestegrupper",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tjenestegrupper",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tjenestegrupper].* FROM [dbo].[Tjenestegrupper] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tjenestegrupper].* FROM [dbo].[Tjenestegrupper] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tjenestegrupper"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Utdanning",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Utdanning",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Utdanning].* FROM [dbo].[Utdanning] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Utdanning].* FROM [dbo].[Utdanning] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Utdanning"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4e9f0201-a402-446a-8143-3524dec0a92e",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "e93c2126-b5fc-4246-b517-1d3e8d5fd7cc",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "7d2da773-d756-403e-b569-1ad00b2f5e9f",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "664363a3-aadb-4475-b62b-318ab1c5d07f",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "31871d8a-ff9e-49ed-be90-1776353945e4",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f6c09549-e3e3-4916-ad78-64e528b3bc32",
        "fromTable": "Alle Data",
        "fromColumn": "Energitypekode",
        "toTable": "Energitype",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "594be1f1-a81a-452e-9716-b79eec7957c4",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonkode",
        "toTable": "Funksjon",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "59939372-74a8-4aeb-bfd6-4cc23ae88a18",
        "fromTable": "Alle Data",
        "fromColumn": "Handsamingstidkode",
        "toTable": "Kilde",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "cf2e5996-1feb-4ea4-8043-5ebfa5c19e6c",
        "fromTable": "Alle Data",
        "fromColumn": "Alderkode",
        "toTable": "Alder",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "dbf8b217-9570-4951-b6bd-b6e2b03b327f",
        "fromTable": "Alle Data",
        "fromColumn": "Handsamingstidkode",
        "toTable": "Handsamingstid",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f77ef936-3e3f-4d7b-afb8-c7e6f0894bc7",
        "fromTable": "Alle Data",
        "fromColumn": "Konklusjonkode",
        "toTable": "Konklusjon",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "aafab56c-d833-4f01-aa89-ebb84720ddbf",
        "fromTable": "Alle Data",
        "fromColumn": "Tiltakskategorikode",
        "toTable": "Tiltakskategori",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "086ee4f8-dbd1-498f-a83f-4ec576faba0c",
        "fromTable": "Alle Data",
        "fromColumn": "Omsorgs-/hjelpetiltakkode",
        "toTable": "Omsorgs-hjelpetiltak",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "29567bbc-14bb-407c-a300-bca620bf10db",
        "fromTable": "Alle Data",
        "fromColumn": "Tjenestegrupperkode",
        "toTable": "Tjenestegrupper",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "8697b357-b5df-4f45-9413-3a008fb72c1b",
        "fromTable": "Alle Data",
        "fromColumn": "Utdanningkode",
        "toTable": "Utdanning",
        "toColumn": "Dimensjonskode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}