{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "VK-SXD0E-002;Reporting_ASSS",
        "connectionString": "Data Source=VK-SXD0E-002;Persist Security Info=false;Integrated Security=SSPI;Initial Catalog=Reporting_ASSS;Provider=SQLNCLI11",
        "impersonationMode": "impersonateAccount",
        "account": "I04\\vk-SvcASSS",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabelgruppe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabelnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabelgruppe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabelnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Variabelgruppe</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabelnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Variabelgruppe</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabelnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Artnavn",
            "dataType": "string",
            "sourceColumn": "Artnavn"
          },
          {
            "name": "ArtkodeNavn",
            "dataType": "string",
            "sourceColumn": "ArtkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Art",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Art].* FROM [dbo].[Art] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ArtkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>131</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ArtkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ArtkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Art].* FROM [dbo].[Art] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Art"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ArtkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>131</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ArtkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ArtkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "ASSS Indikatorer",
        "isHidden": true,
        "columns": [
          {
            "name": "Barnehage",
            "dataType": "int64",
            "sourceColumn": "Barnehage",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Miljøforvaltning",
            "dataType": "int64",
            "sourceColumn": "Miljøforvaltning",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Samferdsel",
            "dataType": "int64",
            "sourceColumn": "Samferdsel",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Barnevern",
            "dataType": "int64",
            "sourceColumn": "Barnevern"
          },
          {
            "name": "Pleie og omsorg",
            "dataType": "int64",
            "sourceColumn": "Pleie og omsorg"
          },
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Byggesak",
            "dataType": "int64",
            "sourceColumn": "Byggesak"
          },
          {
            "name": "Eiendomsforvaltning",
            "dataType": "int64",
            "sourceColumn": "Eiendomsforvaltning"
          },
          {
            "name": "Kommunehelse",
            "dataType": "int64",
            "sourceColumn": "Kommunehelse"
          },
          {
            "name": "Sosiale tjenester",
            "dataType": "int64",
            "sourceColumn": "Sosiale tjenester"
          },
          {
            "name": "Grunnskole",
            "dataType": "int64",
            "sourceColumn": "Grunnskole"
          },
          {
            "name": "VAR",
            "dataType": "int64",
            "sourceColumn": "VAR"
          }
        ],
        "partitions": [
          {
            "name": "ASSS Indikatorer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>149</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>184</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>147</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Grunnskole</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>VAR</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Grunnskole</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>VAR</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Pleie og omsorg</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Andre</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Byggesak</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eiendomsforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kommunehelse</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Sosiale tjenester</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Grunnskole</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>VAR</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "SFS Kommunale veier i km per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var lengde_komvei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "var resultat =",
              "DIVIDE(lengde_komvei, DIVIDE(innb, 10000))",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Antall km tilrettelagt for syklende som kommunen har ansvaret for per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var lengde_syklende = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Lengde  tilrettelagt for syklende som kommunen har ansvaret for (km)\"",
              "    )",
              ")",
              "",
              "var innb_ant = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "var resultat =",
              "DIVIDE(lengde_syklende, DIVIDE(innb_ant, 10000))",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Brutto driftsutgifter eksklusiv avskrivninger samferdsel per km (kroner)",
            "expression": [
              " ",
              "",
              "var agd10 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"332\")",
              ")",
              "",
              "var a590 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),  ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A590\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"332\")",
              ")",
              "",
              "var vei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "var resultat =",
              "DIVIDE((agd10 - a590) * 1000, vei)",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(agd10) || ISBLANK(a590)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            resultat,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnader til gatebelysning per lyspunkt, kommunale veier",
            "expression": [
              "",
              "",
              "var gate = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12183\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutgifter til gatebelysning langs kommunale veier og gater (1000 kr)\")",
              ")",
              "",
              "var lys = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11845\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lyspunkt langs kommunale veier og gater (antall)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE((gate * 1000), lys)",
              "",
              "RETURN (",
              "    ROUND(",
              "        resultat,",
              "        1  ",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Drenering/overvann, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutg eks avskrivninger til drenering/overvann\"",
              "    )",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE(brutto, lengde * 1000)",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Trafikksikkerhet inkludert skilting og veimerking, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto driftsutg eks avskrivninger til trafikksikkerhet inkl skilting og vegmerking\"",
              "    )",
              ")",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE(brutto, lengde * 1000)",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Renhold, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til renhold\")",
              ")",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE(brutto, lengde * 1000)",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Vinterdrift, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til vinterdrift\")",
              ")",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE(brutto, lengde * 1000)",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Investeringer til veidekker (asfalt) per meter vei (kroner)",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Investeringer til veidekker\")",
              ")   ",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE(brutto, lengde * 1000)",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Sykefravær samferdsel (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Samferdsel\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Samferdsel\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Veidekker, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutg eks avskrivninger til veidekker\")",
              ")",
              "",
              "var lengde = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")",
              "",
              "var resultat =",
              "DIVIDE(brutto, lengde * 1000)",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel adkomst- og GS-vei på og/eller over akseptabel standard - tilstandsgrad TG2 (prosent)*",
            "expression": [
              "",
              "",
              "var resultat =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel adkomst- og GS-veg over akseptabelt nivå > TG2\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel gate og samlevei på og/eller over akseptabel standard - tilstandsgrad TG1 (prosent)*",
            "expression": [
              "",
              "",
              "var resultat =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel gate og samleveg over akseptabelt nivå > TG1\"",
              "    )",
              ")",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnad per meter vei for å komme over akseptabel standard (kroner)*",
            "expression": [
              "",
              "",
              "var resultat =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"SFS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Kostnad per meter veg for å komme over akseptabel standard\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "BNV Netto driftsutgifter barnevernstjenester per innbygger 0-17 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"244\", \"251\", \"252\"}),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE((ndrbv*1000), barn),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med undersøkelser i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var barn_und =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12286\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med undersøking  (antall)\")",
              ")",
              "",
              "var pers_017 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barn_und, pers_017) * 100,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med barneverntiltak i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var barn_mtiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-22 år\"),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "var pers_017 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-17 år\")",
              ")",
              "",
              "var formel017 =",
              "DIVIDE(",
              "    barn_mtiltak, ",
              "    pers_017",
              ") * 100",
              "",
              "return (",
              "    ROUND(",
              "        formel017,",
              "        1    ",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med barnevernstiltak i løpet av året  (antall)\"",
              "    ),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-22 år\"),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = ",
              "        \"252 - Barnevernstiltak når barnet er plassert av barnevernet\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn som er plassert i løpet av året i prosent av antall barn 0-17 år",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var barn_017 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-17 år\")",
              ")",
              "",
              "var bnv_tiltak_022 = ",
              "DIVIDE(",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)], ",
              "    barn_017",
              ") * 100",
              "",
              "",
              "return (",
              "    ROUND(",
              "        bnv_tiltak_022,",
              "        2",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-22 år\"),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = ",
              "        \"251 - Barnevernstiltak når barnet ikke er plassert av barnevernet\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn som ikke er plassert i løpet av året i prosent av alle i tiltak (0-22 år)",
            "expression": [
              "",
              "",
              "var tiltak = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med barnevernstiltak i løpet av året  (antall)\"",
              "    ),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-22 år\"),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "var formel_022 =",
              "DIVIDE(",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)],",
              "    tiltak",
              ") * 100",
              "",
              "return (",
              "    ROUND(",
              "        formel_022,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f251) som ikke er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"251\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var formel022 =",
              "DIVIDE(",
              "    brbv, ",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)]",
              ") * 1000",
              "",
              "var formel024 =",
              "DIVIDE(",
              "    brbv, ",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-24 år som ikke er plassert f251 (antall)]",
              ") * 1000",
              "",
              "return (",
              "    ROUND(",
              "        IF(valgte_aar >= 2021, formel024, formel022),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"252\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              " )",
              "",
              "var formel022 =",
              "DIVIDE(",
              "    brbv,",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              ") * 1000",
              "",
              "var formel024 =",
              "DIVIDE(",
              "    brbv,",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-24 år som er plassert f252 (antall)]",
              ") * 1000",
              "",
              "return (",
              "    ROUND(",
              "        IF(valgte_aar >= 2021, formel024, formel022),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel undersøkelser gjennomført i løpet av 3 måneder (prosent)",
            "expression": [
              "",
              "",
              "var avsunder3mnd =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12860\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Undersøkingar avslutta (antall)\"",
              "    ),",
              "    FILTER(ALL(Handsamingstid[Handsamingstidnavn]), ",
              "        [Handsamingstidnavn] = \"Innan 3 månader\")",
              ")",
              "",
              "var avsundertot =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12860\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Undersøkingar avslutta (antall)\"",
              "    ),",
              "    FILTER(ALL(Handsamingstid[Handsamingstidnavn]), ",
              "        [Handsamingstidnavn] = \"Undersøkingar avslutta\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(avsunder3mnd, avsundertot) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Sykefravær barnevern (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Barnevern\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Barnevern\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Netto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var brbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"252\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var formel022 =",
              "DIVIDE(",
              "    brbv * 1000,",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)]",
              ")",
              "",
              "var formel024 =",
              "DIVIDE(",
              "    brbv * 1000,",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-24 år som er plassert f252 (antall)]",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        IF(valgte_aar < 2021, formel022, formel024),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f244 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto244 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"244\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto244, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f251 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto251 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"251\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto251, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel av netto driftsutgifter barnevern f252 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK13\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var netto252 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"252\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(netto252, nettobv) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med melding av innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var melding = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12615\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] =  \"0-17 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(melding, barn) * 100,",
              "        1",
              "    )",
              ")",
              "    ",
              ""
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Antall barn med undersøkelse eller tiltak per årsverk (funksjon 244)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12280\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Stillinger med fagutdanning av alle fag- og tiltaksstillinger (prosent)",
            "expression": [
              "",
              "",
              "var fag = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12305\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Stillingar med fagutdanning (årsverk)\"",
              "    )",
              ")",
              "",
              "var stillinger = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12305\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(fag, stillinger) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel meldinger som går til undersøkelser (prosent)",
            "expression": [
              "",
              "",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12189\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Meldingar til barnevernet (antall)\"",
              "    ),",
              "    FILTER(ALL('Konklusjon på meldinga'[Konklusjon på meldinganavn]), ",
              "        [Konklusjon på meldinganavn] = \"Til undersøkelse\"),",
              "    FILTER(ALL('Handsamingstid av meldinga'[Handsamingstid av meldinganavn]), ",
              "        [Handsamingstid av meldinganavn] = \"Meldinger i alt\"",
              "    )",
              ")",
              "",
              "var meld = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12189\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Meldingar til barnevernet (antall)\"",
              "    ),",
              "    FILTER(ALL('Handsamingstid av meldinga'[Handsamingstid av meldinganavn]), ",
              "        [Handsamingstid av meldinganavn] = \"Meldinger i alt\"",
              "    ),",
              "    FILTER(ALL('Konklusjon på meldinga'[Konklusjon på meldinganavn]), ",
              "        [Konklusjon på meldinganavn] = \"Meldinger i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, meld) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "PLO Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 0 til 66 år",
            "expression": [
              "",
              "",
              "var behov1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var behov2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, middels bistandsbehov, 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var behov3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere,  omfattende bistandsbehov,  0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(behov1) || ISBLANK(behov2) || ISBLANK(behov3)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                (behov1 * 1) + (behov2 * 2) + (behov3 * 3),",
              "                behov1 + behov2 + behov3",
              "            ),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Gjennomsnittlig bistandsbehov hos mottakere av hjemmetjenester 67 år+",
            "expression": [
              "",
              "",
              "var behov1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, noe/avgrenset bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var behov2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, middels bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var behov3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "        \"Hjemmetjenestebrukere, omfattende bistandsbehov, 67 år og over (antall)\"",
              "    )",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(behov1) || ISBLANK(behov2) || ISBLANK(behov3)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                (behov1 * 1) + (behov2 * 2) + (behov3 * 3),",
              "                behov1 + behov2 + behov3",
              "            ),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere i institusjon som har omfattende bistandsbehov: Langtidsopphold (prosent)",
            "expression": [
              "",
              "",
              "var beb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - beboere på langtidsopphold (antall)\")",
              ")",
              "",
              "",
              "var bebomf = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Institusjon - beboere på langtidsopphold, omfattende bistandsbehov (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(bebomf, beb) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel timer hjemmetjeneste brukere 0-66 år",
            "expression": [
              "",
              "",
              "var timer1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\"",
              "    )",
              ")",
              "var brukere1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var timer2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\"",
              "    )",
              ")",
              "var brukere2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"67-79 år\",",
              "        \"80 år og over\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var antall_timer_66 =",
              "timer1 * brukere1",
              "",
              "var antall_timer_67 =",
              "timer2 * brukere2",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(timer1) || ISBLANK(brukere1) ||",
              "    ISBLANK(timer2) || ISBLANK(brukere2) ||",
              "    ISBLANK(antall_timer_66) || ISBLANK(antall_timer_67)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                antall_timer_66,",
              "                antall_timer_66 + antall_timer_67",
              "            ) * 100,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel timer hjemmetjeneste brukere 67 år +",
            "expression": [
              "",
              "",
              "var timer1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 0-66 år (antall)\"",
              "    )",
              ")",
              "var brukere1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var timer2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig antall tildelte timer i uken, hjemmetjenestebrukere 67 år og over (antall)\"",
              "    )",
              ")",
              "var brukere2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"67-79 år\",",
              "        \"80 år og over\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(timer1) || ISBLANK(timer2) || ISBLANK(brukere1) ||",
              "    ISBLANK(brukere2)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                timer2 * brukere2,",
              "                timer1 * brukere1 + brukere2 * timer2",
              "            ) * 100,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 0-66 år per innbygger 0-66 år (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"254\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(netto066)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 0-66 år], 100) * 1000,",
              "                bef",
              "            ),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 67 + år per innbygger 67 år+ (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"254\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"67 år og over\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(netto066)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 67 år +], 100) * 1000,",
              "                bef",
              "            ),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 0-66 år som er beboere på institusjon eller mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Institusjonstenester\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(gr1) || ISBLANK(gr2)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(gr1 + gr2, bef) * 100,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 80 år og eldre som mottar hjemmetjenester (prosent)",
            "expression": [
              "",
              "",
              "var br80he = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"80 år og over\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var pe80 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"80 år og over\")",
              ")",
              " ",
              "return (",
              "    ROUND(",
              "        DIVIDE(br80he, pe80) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel innbyggere 80 år+ beboer på institusjon eller i bolig med heldøgns bemanning(prosent)",
            "expression": [
              "",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beboere 80 år og over i bolig m/ fast tilknyttet bemanning hele døgnet (antall)\")",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - beboere 80 år og over (antall)\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] =\"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"80 år og over\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(gr1) || ISBLANK(gr2)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(gr1 + gr2, bef) * 100,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere på institusjon 0-66 år (prosent)",
            "expression": [
              "",
              "",
              "var br066inst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Institusjonstenester\")",
              ")",
              "",
              "var braltinst = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Institusjonstenester\")",
              ")",
              "",
              "return (",
              "   ROUND(",
              "        DIVIDE(br066inst, braltinst) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Brutto driftsutgifter per plass i institusjon (kroner)",
            "expression": [
              "",
              "",
              "var brutg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {",
              "        \"253\", ",
              "        \"261\"",
              "    }),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var plasser = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11875\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Institusjon - alle disponible plasser (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brutg * 1000, plasser),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 0-66 år per mottaker 0-66 år (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"254\")",
              "    ",
              ")",
              "",
              "var mott066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 - 66 år\"),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(netto066)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 0-66 år], 100) * 1000,",
              "                mott066",
              "            ),",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Netto driftsutgifter hjemmetjeneste 67 + år per mottaker 67 år+ (kroner)",
            "expression": [
              "",
              "",
              "var netto066 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"254\")",
              ")",
              "",
              "var mott67= ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12003\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brukere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"67-79 år\",",
              "        \"80 år og over\"",
              "    }),",
              "    FILTER(ALL(Tjenestegrupper[Tjenestegruppernavn]), [Tjenestegruppernavn] = \"Heimeteneste\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(netto066)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                netto066 * DIVIDE([PLO Andel timer hjemmetjeneste brukere 67 år +], 100) * 1000,",
              "                mott67",
              "            ),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel årsverk i brukerrettede tjenester med fagutdanning (prosent)",
            "expression": [
              "",
              "",
              "var gr1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "    \"Årsverk i brukerrettede tjenester m/ helseutdanning fra videregående skole (antall)\", ",
              "    \"Årsverk i brukerrettede tjenester m/ helseutdanning fra høyskole/universitet (antall)\"",
              "    })",
              ")",
              "",
              "var gr2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11924\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] = \"Omsorgstjenestene i alt\")",
              ")",
              "",
              "var gr3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11924\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] IN {",
              "        \"Administrativt personell\",",
              "        \"Servicefunksjon\"",
              "    })",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(gr2) || ISBLANK(gr3)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(gr1, gr2 - gr3) * 100,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Sykefravær pleie og omsorg (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Pleie og omsorg\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Pleie og omsorg\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Legetimer per uke per beboer i sykehjem (timer)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12293\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Legetimer per uke per beboer i sykehjem (timer)\")",
              ")",
              "",
              "return (",
              "    ROUND(a, 2)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel utviklingshemmede av befolkningen 16 år og eldre (TTU) (prosent)*",
            "expression": [
              "",
              "",
              "var utv16 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel utviklingshemmede av befolkningen 16 år og eldre (TTU) (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(utv16, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Utgifter per utviklingshemmet (fratrukket refusjon ressurskrevende) (TTU) (kroner)*",
            "expression": [
              "",
              "",
              "var utgutv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter per utviklingshemmet (fratrukket refusjon ressurskrevende) (TTU) (kroner)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(utgutv, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel utviklingshemmede 18 år+ i bolig med fast tilknyttet personell hele døgnet (TTU)(prosent)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel utviklingshemmede 18 år og eldre som bor i bolig med fast tilknyttet personell hele døgnet (TTU) (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Utgifter bolig med fast personell hele døgnet (inkl. private/ideelle) per beboer (TTU) (kroner)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter til bolig med fast tilknyttet personell hele døgnet (inkl. private/ideelle) per beboer (TTU) (kroner)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel årsverk med fagutdanning (TTU) (prosent)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"TTU01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel årsverk med fagutdanning (TTU) (prosent)\")",
              ")",
              "",
              "return (",
              "    ROUND(a, 1)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "BNV Andel barn med tiltak 0-5 år av barn på tiltak 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var antall1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Tiltak i alt\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \" 0 - 5 år\")",
              ")",
              "",
              "var antall2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Tiltak i alt\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \" 0 - 5 år\",",
              "        \" 6 - 12 år\",",
              "        \"13 - 17 år\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(antall1, antall2) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "KHT Netto driftsutgifter kommunehelsetjenesten per innbygger (kroner)",
            "expression": [
              "",
              "",
              "var nettokom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] in ",
              "        {\"232\", \"233\", \"241\"}",
              "    ) ",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettokom * 1000, bef),",
              "        0",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Netto driftsutgifter kommunehelsetjenesten av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "",
              "var nettokom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN ",
              "        {\"232\", \"233\", \"241\"}",
              "    )",
              ")",
              "",
              "var nettoalle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Netto driftsutgifter totalt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettokom, nettoalle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsestasjonen totalt per 10 000 innbyggere 0-20 år",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] = \"Utdanning i alt\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsesykepleiere totalt per 10 000 innbyggere 0-20 år",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] = \"Helsesykepleiere\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk leger per 10 000 innbyggere (f120, f233, f241)",
            "expression": [
              "",
              "",
              "var aarsverk1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11996\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte legeårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Avtaleformnavn]), [Avtaleformnavn] = \"Avtaleform i alt\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN ",
              "        {\"120\", \"233\", \"241\"}",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk1, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Brutto driftsutgifter (f232, f233 og f241) per innbygger (kroner)",
            "expression": [
              "",
              "",
              "var brkom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN ",
              "        {\"232\", \"233\", \"241\"}",
              "    ),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "var person = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brkom * 1000, person),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Ledig liste-kapasitet",
            "expression": [
              "",
              "",
              "var kapasitet = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Kapasitet hos fastlegene (iht. liste) (antall)\"",
              "    )",
              ")",
              "",
              "var pasienter = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    /* Tilsvarer \"Antall pasienter på fastlegeliste med lege (antall)\" på ssb.no */",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall pasienter på fastlegeliste med lege (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(kapasitet, pasienter) * 100 ,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Ledig liste-kapasitet i prosent av antall innbyggere",
            "expression": [
              "",
              "",
              "var kapasitet = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Kapasitet hos fastlegene (iht. liste) (antall)\"",
              "    )",
              ")",
              "",
              "var pasienter = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12005\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall pasienter på fastlegeliste med lege (antall)\"",
              "    )",
              "",
              ")",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(kapasitet) || ISBLANK(pasienter)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(kapasitet - pasienter, bef) * 100,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Andel nyfødte med hjembesøk innen 2 uker etter hjemkomst (prosent)",
            "expression": [
              "",
              "",
              "var fodte = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = ",
              "        \"Hjemmebesøk av helsesykepleier til nyfødte\"",
              "    )",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(fodte, barn) * 100 ,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Sykefravær kommunehelse (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Kommunehelse\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Kommunehelse\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk ergoterapeuter per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "/* totalt årsverk */",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer i alt\"",
              "    )",
              ")",
              "",
              "/* totale befolkning */",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, bef) * 10000 , ",
              "        1 ",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsestasjonen totalt per 1 000 innbyggere 0-5 år",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\"",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Netto driftsutgifter forebygging, helsestasjons- og skolehelsetjeneste per innb. 0-20 år(kroner)",
            "expression": [
              "",
              "",
              "var nettokom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"232\")",
              "    ",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettokom * 1000, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk helsesykepleiere per 1 000 innbygger 0-5 år",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk helsesykepleiere uten ledelse. Helsestasjon 0-5 år\"",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk totalt på helsestasjon per innbygger 0-5 år",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\"",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, bef),",
              "        4",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelsetjenesten per 1 000 elever barnetrinn",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk barnetrinn totalt uten ledelse. Skolehelse barnetrinn\"",
              "    )",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale og private grunnskoler (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] IN {",
              "        \"1.-4. trinn\",",
              "        \"5.-7. trinn\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(elev, 1000)),",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelsetjenesten per 1 000 elever ungdomstrinn",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ungdomstrinn totalt uten ledelse. Skolehelse ungdomstrinn\"",
              "    )",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] =  \"8.-10. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(elev, 1000)),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk skolehelse per innbygger 16-20 år VGS",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk vg skole totalt uten ledelse. Skolehelse videregående skole\"",
              "    )",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), ",
              "        IF(ISERROR(VALUE(LEFT([Aldernavn], 3))) || LEN([Aldernavn]) > 5, ",
              "            BLANK(), ",
              "            VALUE(LEFT([Aldernavn], 3)) >= 16 && VALUE(LEFT([Aldernavn], 3)) <= 20",
              "        )",
              "    )",
              "    ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, elev),",
              "        5",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk kommunale fysioterapeuter i alt per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Avtaleformnavn]), [Avtaleformnavn] = \"Avtaleform i alt\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK10\")",
              ")",
              "",
              "var aarsverk241 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Avtaleformnavn]), [Avtaleformnavn] = \"Avtaleform i alt\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"241\")",
              ")",
              "",
              "var aarsverkfast = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Avtaleformnavn]), [Avtaleformnavn] = \"Fastlønnet\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"241\")",
              "    ",
              ")",
              "",
              "var aarsverkturnus = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Avtaleformnavn]), [Avtaleformnavn] = \"Turnusfysioterapeut\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"241\")  ",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "var fgk10min241 =",
              "aarsverk - aarsverk241",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(aarsverk) || ISBLANK(aarsverk241) || ISBLANK(aarsverkfast)",
              " || ISBLANK(aarsverkturnus)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(",
              "                fgk10min241 + aarsverkfast + aarsverkturnus,",
              "                DIVIDE(bef, 10000)",
              "            ),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk private fysioterapeuter i alt per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11995\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK10\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte fysioterapeutårsverk (årsverk)\"),",
              "    FILTER(ALL(Avtaleform[Avtaleformnavn]), [Avtaleformnavn] = \"Tilskudd\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 10000)),",
              "        1",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk jordmor per 10 000 fødte",
            "expression": [
              "",
              "",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] = \"Jordmødre\")",
              ")",
              "",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, DIVIDE(var2, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk leger per 10 000 innbyggere 0-5 år",
            "expression": [
              "",
              "",
              "var var1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11994\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte årsverk (årsverk)\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] = \"Leger\")",
              ")",
              "",
              "var var2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] =\"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(var1, DIVIDE(var2, 10000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Spedbarnundersøkelse 8. leveuke (prosent)",
            "expression": [
              "",
              "",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt 8.leveuke\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Fødte i løpet av året (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, barn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Helseundersøkelse 2-3 år (prosent)",
            "expression": [
              "",
              "",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"2-3 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, DIVIDE(barn, 2)) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Helseundersøkelse 4 år (prosent)",
            "expression": [
              "",
              "",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"4 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, barn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Helseundersøkelse 1. trinn (prosent)",
            "expression": [
              "",
              "",
              "var und = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt grunnskole 1.trinn\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"5-6 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(und, DIVIDE(barn, 2)) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Målt produksjon helsestasjon",
            "expression": [
              "",
              "",
              "var undGrav = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13533\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall nyinnskrevne gravide som har møtt til svangerskapskontroll (antall)\"",
              "    )",
              ")",
              "",
              "var undFG = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = ",
              "        \"Hjemmebesøk av helsesykepleier til nyfødte\"",
              "    )",
              ")",
              "",
              "var und8 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt 8.leveuke\")",
              ")",
              "",
              "var und23 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var und4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var arsverkhst05 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\"",
              "    )",
              ")",
              "",
              "/* Returnerer true hvis en av verdiene er blanke */",
              "",
              "var vekthstprod = ",
              "(0.21*undGrav)+(0.31*undFG)+(0.16*und8)+(0.16*und23)+(0.16*und4)",
              "",
              "var resultat =",
              "DIVIDE(vekthstprod, arsverkhst05)",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(undGrav) || ISBLANK(undFG) || ISBLANK(und8) || ISBLANK(und23) || ISBLANK(und4) || ",
              "    ISBLANK(arsverkhst05)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            resultat,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Konsultasjon og sykebesøk per 1 000 innbyggere",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KPR01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"2 konsultasjon Alle aldre Antall pasienter per 1 000 innbyggere\"",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "EIE Netto driftsutgifter eiendomsforvaltning av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "",
              "var nettoeien = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var nettoalle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Netto driftsutgifter totalt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettoeien, nettoalle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Samlet areal på formålsbyggene i kvadratmeter per innbygger",
            "expression": [
              "",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Areal totalt\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(areal, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Korrigerte brutto driftsutgifter til kommunal eiendomsforvaltning per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var korrbreien = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6a\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Areal totalt\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(korrbreien * 1000, areal),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Korrigerte brutto driftsutgifter eksklusiv avskrivninger per kvadratmeter eiet bygg (kroner)",
            "expression": [
              "",
              "",
              "var brutto = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var avskr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A590\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var leie = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A190\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6a\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var leieavs =",
              "leie + avskr",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(brutto) || ISBLANK(leieavs)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(brutto - leieavs, areal) * 1000,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Utgifter til renholdsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var renhold = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12905\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD38\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(renhold * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Korrigert brutto driftsutgifter til kommunal forvaltning av eiendommer per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var korrbreien = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"121\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Areal totalt\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(korrbreien * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Utgifter til driftsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var drift = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12905\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD39\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(drift * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Utgifter til vedlikeholdsaktiviteter i kommunal eiendomsforvaltning, per kvadratmeter (kroner)",
            "expression": [
              "",
              "",
              "var ved = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12905\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD36\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")   ",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ved * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Sykefravær eiendomsforvaltning (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Eiendomsforvaltning\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Eiendomsforvaltning\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Samlet energibruk i kommunal eiendomsforvaltning kWh/m2",
            "expression": [
              "",
              "",
              "var energi = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12150\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Energibruk (MWh)\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "var areal = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11906\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn]=\"Areal (m2)\"),",
              "    FILTER(ALL(Eieform[Eieformnavn]), [Eieformnavn] = \"Eid areal\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(energi * 1000, areal),",
              "        1",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "SFS Brutto investeringsutgifter til kommunale veier og gater per innbygger (kroner)*",
            "expression": [
              "",
              "",
              "var resultat =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11816\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Brutto investeringsutgifter til kommunale veier og gater per innbygger (kr)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1   ",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SOS Netto driftsutgifter til sosialtjenesten(f242/f243/f273/f276/f281) pr innbygger 18-66 år(kroner)",
            "expression": [
              "",
              "",
              "var ndrsos = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN ",
              "        {\"242\", \"243\", \"273\", \"276\", \"281\"}",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndrsos * 1000, [SOS Antall innbyggere 18-66]),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Netto driftsutgifter til ytelse til livsopphold (f281) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "",
              "var ndr281 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"281\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr281 * 1000, [SOS Antall innbyggere 18-66]),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Netto driftsutgifter tilbud personer med rusproblemer (f243) per innbygger 18-66 år (kroner)",
            "expression": [
              "",
              "",
              "var ndr243 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"243\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr243 * 1000, [SOS Antall innbyggere 18-66]),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere 18-66 år av innbyggere 18-66 år (prosent)",
            "expression": [
              "",
              "",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpstilfeller (antall)\")",
              ")",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"18-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sosmott, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere 18-24 år av innbyggere 18-24 år (prosent)",
            "expression": [
              "",
              "",
              "var sosmot = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpstilfeller 18-24 år (antall)\")",
              ")",
              "",
              "var bef =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"18-24 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sosmot, bef) * 100 ,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere 25-66 år av innbyggere 25-66 år (prosent)",
            "expression": [
              "",
              "",
              "var sosmot = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpstilfeller 25-66 år (antall)\")",
              ")",
              "",
              "var bef =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"25-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(sosmot, bef) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall mottakere av kvalifiseringsstønad (f276) per 1 000 innbyggere 18-66 år",
            "expression": [
              "",
              "",
              "var delt = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12160\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Deltakere (antall)\")",
              ")",
              "",
              "var bef =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"18-66 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(delt, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Stønad (bidrag+lån) per sosialhjelpsmottaker (kroner)",
            "expression": [
              "",
              "",
              "var stonad = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Samlet stønadssum (bidrag + lån)  (kr)\") ",
              ")",
              "",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpstilfeller (antall)\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(stonad, sosmott),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel med sosialhjelp som hovedinntekt/mottak i 6 mnd eller mer (alle mottakere/aldre) (prosent)",
            "expression": [
              "",
              "",
              "var langtid = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12213\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpstilfeller 6 måneder eller mer og sosialhjelp som hovedinntekt  (antall)\"",
              "    ) ",
              ") ",
              "",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpstilfeller (antall)\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(langtid, sosmott) * 100 ,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Stønadslengde sosialhjelpsmottakere 18-24 år. Gjennomsnittlig antall måneder per år*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Gjennomsnittlig stønadstid 18-24 år (antall)\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Etter KVP: Andel deltakere som gikk til arbeid/skole/utdanning (prosent)*",
            "expression": [
              "",
              "",
              "var anddelt =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KVP01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Etter KVP: Andel deltakere som gikk arbeid/skole/utdanning\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(anddelt, 2)",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Sykefravær sosiale tjenester (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Sosiale tjenester\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Sosiale tjenester\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Andel sosialhjelpsmottakere som forsørger barn under 18 år (prosent)",
            "expression": [
              "",
              "",
              "var langtid = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpstilfeller som forsørger barn under 18 år (antall)\"",
              "    ) ",
              ") ",
              "var sosmott = ",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpstilfeller (antall)\") ",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(langtid, sosmott) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Stønadslengde mottakere med sosialhjelp som hovedinntektskilde. Snitt måneder per år*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12213\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig stønadslengde for tilfeller med sosialhjelp som hovedinntekt  (måneder)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall sosialhjelpsmottakere som forsørger barn under 18 år",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]), ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpsmottakere som forsørger barn under 18 år (antall)\"",
              "    ) ",
              ") "
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall sosialhjelpsmottakere av innbyggere 18-66 år",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13138\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sosialhjelpsmottakere (antall)\")",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Sosialhjelpsmottakere med sosialhjelp som viktigste kilde til livsopphold (antall)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12203\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Sosialhjelpsmottakere med sosialhjelp som viktigste kilde til livsopphold (antall)\"",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Gjennomsnittlig stønadslengde med sosialhjelp som hovedinntekt (måneder)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12213\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Gjennomsnittlig stønadslengde for mottakere med sosialhjelp som hovedinntekt  (måneder)\"",
              "    )",
              ")",
              "",
              "",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Brutto driftsutgifter til sosialtjenesten (f242/f243/f273/f276/f281) (kroner)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"242\", \"243\", \"273\", \"276\", \"281\"})",
              ")",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Netto driftsutgifter til sosialtjenesten (f242/f243/f273/f276/f281) (kroner)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"242\", \"243\", \"273\", \"276\", \"281\"})",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "SOS Antall innbyggere 18-66",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"18-66 år\")",
              ")",
              ""
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "BHG Netto driftsutgifter barnehager per innbygger 1-5 år (kroner)",
            "expression": [
              "",
              "",
              "var nettobhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"201\", \"211\", \"221\"})",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"1-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettobhg * 1000, bef),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Netto driftsutgifter barnehager av kommunens samlede netto driftsutgifter (prosent)",
            "expression": [
              "",
              "",
              "var nettobhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"201\", \"211\", \"221\"})",
              ")",
              "",
              "var nettoalle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Netto driftsutgifter totalt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(nettobhg, nettoalle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Andel minoritetsspråklige barn i barnehage i forhold til innvandrerbarn (prosent)",
            "expression": [
              "",
              "",
              "var minbarn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Minoritetsspråklige barn (antall)\")",
              ")",
              "",
              "var innbarn =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innvandrerbarn (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(minbarn, innbarn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 1-2 år i barnehage av innbyggere 1-2 år (prosent)",
            "expression": [
              "",
              "",
              "var barnbhg12 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"1-2 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barn12 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"1-2 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnbhg12, barn12) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 3-5 år i barnehage av innbyggere 3-5 år (prosent)",
            "expression": [
              "",
              "",
              "var barnbhg35 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"3-5 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barn35 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"3-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnbhg35, barn35) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 1-5 år i barnehage av innbyggere 1-5 år (prosent)",
            "expression": [
              "",
              "",
              "var bhgbarn15 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\")",
              ")",
              "",
              "var allebarn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"1-5 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(bhgbarn15, allebarn) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Minoritetsspråklige barn i barnehage av alle barnehagebarn 1-5 år (prosent)",
            "expression": [
              "",
              "",
              "var minorbhgbarn15 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Minoritetsspråklige barn (antall)\")",
              ")",
              "",
              "var bhgbarn15 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(minorbhgbarn15, bhgbarn15) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn i kommunale barnehager av alle barn i barnehage (prosent)",
            "expression": [
              "",
              "",
              "var barnkom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommune\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]=\"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnkom, barnbhg) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn i private barnehager av alle barn i barnehage (prosent)",
            "expression": [
              "",
              "",
              "var barnkom = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Privat\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barnbhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-6 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnkom, barnbhg) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Andel menn av grunnbemanningen barnehager (prosent)",
            "expression": [
              "",
              "",
              "var ansatte = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12129\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte (antall)\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Stillingstype[Stillingstypenavn]), [Stillingstypenavn] IN {",
              "        \"Annen grunnbemanning\",",
              "        \"Pedagogisk leder\",",
              "        \"Styrer\"",
              "    })",
              ")",
              "",
              "var menn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12129\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte (antall)\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Mann\"),",
              "    FILTER(ALL(Stillingstype[Stillingstypenavn]), [Stillingstypenavn] IN {",
              "        \"Annen grunnbemanning\",",
              "        \"Pedagogisk leder\",",
              "        \"Styrer\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(menn, ansatte) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Korrigerte brutto driftsutgifter f201 per korrigert oppholdstime i kommunale barnehage (kroner)",
            "expression": [
              "",
              "",
              "var kbr201 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD4\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"201\")",
              ")",
              "",
              "var kopph = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12216\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Korrigerte oppholdstimer (timer)\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommune\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(kbr201 * 1000, kopph),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Antall barn per ansatt kommunale barnehager*",
            "expression": [
              "",
              "",
              "var a =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BHG01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn per ansatt i barnehagen (bemanningstetthet)\"",
              "    ),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        a,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Antall barn per ansatt private barnehager*",
            "expression": [
              "",
              "",
              "var a =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BHG01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn per ansatt i barnehagen (bemanningstetthet)\"",
              "    ),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Privat\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        a,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Ansatte med barnehagelærerutdanning/annen pedagogisk utdanning av alle ansatte (prosent)",
            "expression": [
              "",
              "",
              "var utd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"09345\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] IN {",
              "        \"Fylkeskommune/stat\",",
              "        \"Kommune\",",
              "        \"Privat\"",
              "    }),",
              "    FILTER(ALL('Personellets utdanning'[Personellets utdanningnavn]), [Personellets utdanningnavn] IN {",
              "        \"Barnehagelærer\",",
              "        \"Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder\"",
              "    })",
              ")",
              "",
              "var ansatte = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12129\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ansatte (antall)\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] IN  {",
              "        \"Kvinne\",",
              "        \"Mann\"",
              "    }),",
              "    FILTER(ALL(Stillingstype[Stillingstypenavn]), [Stillingstypenavn] = \"Alle stillingstyper\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(utd, ansatte) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Sykefravær barnehager (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Barnehage\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Barnehage\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Barn 1-5 år i barnehage (antall)",
            "expression": [
              "",
              "",
              "var b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12272\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\")",
              ")",
              "",
              "",
              "var a = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0 år\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Alle eierforhold\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(a) || ISBLANK(b)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            a + b,",
              "            1 ",
              "        )",
              "    )",
              ")",
              "",
              ""
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BHG Antall barn per barnehagelærer kommunale barnehager",
            "expression": [
              "",
              "",
              "var bhg = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12436\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Årsverk\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommune\"),",
              "    FILTER(ALL(Stillingstype[Stillingstypenavn]), [Stillingstypenavn] = \"Grunnbemanning\"),",
              "    FILTER(ALL(Utdanning[Utdanningnavn]), [Utdanningnavn] IN {",
              "        \"Barnehagelærer\", ",
              "        \"Pedagogisk utdanning som tilsvarer utdanningskravet til styrer/pedagogisk leder\"",
              "    })",
              ")",
              " ",
              "var barn1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0 år\", ",
              "        \"1-2 år\"",
              "    }),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommune\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var barn2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12056\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn i barnehage (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"3-5 år\",",
              "        \"6 år\"",
              "    }),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommune\"),",
              "    FILTER(ALL(Oppholdstid[Oppholdstidnavn]), [Oppholdstidnavn] = \"Alle oppholdskategorier\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(barn1) || ISBLANK(barn2)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE((barn1 * 2) + barn2, bhg),",
              "            1 ",
              "        )",
              "    )",
              ")",
              "",
              "/*Barn er korrigert ut fra endret vekt - dette er ikke korrigert hos SSB*/",
              "/*27.3.2019 Laila */"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "GRS Netto driftsutgifter grunnskole (f202) per elev (kroner)",
            "expression": [
              "",
              "",
              "var ndr202 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"202\")",
              ")",
              "",
              "var elev = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11977\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr202 * 1000, elev),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Gruppestørrelse (antall)",
            "expression": [
              "",
              "",
              "var etalle =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12285\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elevtimer (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "var ltmmf =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12285\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærertimer minus morsmål og finsk (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(etalle, ltmmf),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler som får spesialundervisning (prosent)",
            "expression": [
              "",
              "",
              "var elspes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "var elall = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale og private grunnskoler (antall)\"),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(elspes, elall) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Årstimer til spesialundervisning per elev med spesialundervisning (antall)",
            "expression": [
              "",
              "",
              "var aartspes =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11974\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årstimer til spesialundervisning, kommunale og private grunnskoler (antall)\"",
              "    )",
              ")",
              "",
              "var antelevspes =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"Elever alle trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aartspes, antelevspes),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever med direkte overgang fra vg1 til vg2 (prosent)",
            "expression": [
              "",
              "",
              "var a =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12236\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever som var registrert i videregående opplæring vg2 samme år som avsluttet vg1 (antall)\"",
              "    )",
              ")",
              "",
              "var b = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12236\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever som avsluttet vg1 (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(a, b) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Nasjonale prøver 5. trinn, snitt andel nivå 2-3 (prosent)*",
            "expression": [
              "",
              "",
              "var les = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 2\", ",
              "        \"Nasjonale prøver Trinn 5: Lesing Mestringsnivå 3\"",
              "    })",
              ")",
              "var regn = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 5: Regning Mestringsnivå 2\", ",
              "        \"Nasjonale prøver Trinn 5: Regning Mestringsnivå 3\"",
              "    })",
              ")",
              "",
              "var eng = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 2\", ",
              "        \"Nasjonale prøver Trinn 5: Engelsk Mestringsnivå 3\"",
              "    })",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(les) || ISBLANK(regn) || ISBLANK(eng)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(les + regn + eng, 3),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Nasjonale prøver 8. trinn, snitt andel nivå 3-5 (prosent)*",
            "expression": [
              "",
              "",
              "var les = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 8: Lesing Mestringsnivå 5\"",
              "    })",
              ")",
              "var regn = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 8: Regning Mestringsnivå 5\"",
              "    })",
              ")",
              "",
              "var eng = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 8: Engelsk Mestringsnivå 5\"",
              "    })",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(les) || ISBLANK(regn) || ISBLANK(eng)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(les + regn + eng, 3),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Nasjonale prøver 9. trinn, snitt andel nivå 3-5 (prosent)*",
            "expression": [
              "",
              "",
              "var les = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 9: Lesing Mestringsnivå 5\"",
              "    })",
              ")",
              "var regn = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] IN {",
              "        \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 3\", ",
              "        \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 4\",",
              "        \"Nasjonale prøver Trinn 9: Regning Mestringsnivå 5\"",
              "    })",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(les) || ISBLANK(regn)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(les + regn, 2),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Sykefravær grunnskole (prosent)",
            "expression": [
              "",
              "",
              "var avtalte_dagsverk =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Grunnskole\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Avtalte dagsverk\")",
              ")",
              "",
              "var sykefravaer =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"FEL01\"),",
              "    FILTER(ALL(Eierforhold[Eierforholdnavn]), [Eierforholdnavn] = \"Kommunal\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Grunnskole\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Sykefraværsdagsverk (legemeldt)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(sykefravaer, avtalte_dagsverk) * 100",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Eksamen snitt engelsk, regning og norsk*",
            "expression": [
              "",
              "",
              "var eng = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Engelsk skriftlig eksamen\")",
              ")",
              "var regn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Matematikk skriftlig eksamen\")",
              ")",
              "var n1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Norsk hovedmål skriftlig eksamen\")",
              ")",
              "",
              "var n2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS04\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Norsk sidemål skriftlig eksamen\")",
              ")",
              "",
              "var n1n2d2 =",
              "DIVIDE(n1 + n2, 2)",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(n1) || ISBLANK(n2) || ISBLANK(eng) || ISBLANK(regn)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(n1n2d2 + eng + regn, 3),",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Vurdering for læring (snitt skår)*",
            "expression": [
              "",
              "",
              "var a = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS05\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elevundersøkelsen Trinn 10: Vurdering for læring\")",
              "",
              ")",
              "var b = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS05\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elevundersøkelsen Trinn 7: Vurdering for læring\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(a) || ISBLANK(b)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(a + b, 2),",
              "            2",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (prosent)",
            "expression": [
              "",
              "",
              "var saer = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12234\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever i kommunale og private grunnskoler som får særskilt norsksopplæring (antall)\"",
              "    )",
              ")",
              "",
              "var alleelev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12234\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] =",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(saer, alleelev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Netto driftsutgifter skoleskyss (f223) per elev (kroner)",
            "expression": [
              "",
              "",
              "var ndr223 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"223\")",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11977\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale grunnskoler, vektet (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(ndr223 * 1000, elev),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 40 år og yngre (prosent)",
            "expression": [
              "",
              "",
              "var l40 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"40 år og yngre\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l40, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 41 - 49 år (prosent)",
            "expression": [
              "",
              "",
              "var l4049 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"41 til 49 år\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l4049, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 50 - 59 år (prosent)",
            "expression": [
              "",
              "",
              "var l5059 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"50 til 59 år\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l5059, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere i grunnskolen 60 år og eldre (prosent)",
            "expression": [
              "",
              "",
              "var l60 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"60 år og eldre\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12282\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"Alle aldersgrupper\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(l60, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Gjennomsnittlig antall elever per kommunale skole",
            "expression": [
              "",
              "",
              "var elever = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11971\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Elever i kommunale skoler (antall)\")",
              ")",
              "",
              "var skoler = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11971\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Kommunale grunnskoler (antall)\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(elever, skoler),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler med spesialundervisning, 1.-4. trinn (prosent)",
            "expression": [
              "",
              "",
              "var spes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"1.-4. trinn\") ",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"1.-4. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(spes, elev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler med spesialundervisning, 5.-7. trinn (prosent)",
            "expression": [
              "",
              "",
              "var spes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"5.-7. trinn\") ",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"5.-7. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(spes, elev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Antall assistentårsverk per hundre lærerårsverk*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"GRS06\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall assistentårsverk per hundre lærerårsverk\"",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere med universitets-/høgskoleutdanning med pedagogisk utdanning (prosent)",
            "expression": [
              "",
              "",
              "var unihogutd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Kompetansenavn]), [Kompetansenavn] = \"Universitets-/høgskoleutdanning, med pedagogisk utdanning\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Kompetansenavn]), [Kompetansenavn] = \"Kompetanse i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(unihogutd, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere med universitets-/høgskoleutdanning uten pedagogisk utdanning (prosent)",
            "expression": [
              "",
              "",
              "var unihogutd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Kompetansenavn]), [Kompetansenavn] = \"Universitets-/høgskoleutdanning, uten pedagogisk utdanning\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Kompetansenavn]), [Kompetansenavn] = \"Kompetanse i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(unihogutd, alle) * 100,",
              "        1",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Lærere med videregående utdanning eller lavere (prosent)",
            "expression": [
              "",
              "",
              "var vgsutd = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Kompetansenavn]), [Kompetansenavn] = \"Videregående utdanning eller lavere\")",
              ")",
              "",
              "var alle = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12247\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lærere (antall)\"),",
              "    FILTER(ALL('Kjønn'[Kjønnnavn]), [Kjønnnavn] = \"Begge kjønn\"),",
              "    FILTER(ALL(Kompetanse[Kompetansenavn]), [Kompetansenavn] = \"Kompetanse i alt\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(vgsutd, alle) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "BNV Andel barn med tiltak per 31.12 med utarbeidet plan (prosent)",
            "expression": [
              "",
              "",
              "var barnmutplan = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med tiltak per 31.12. med utarbeidet plan\")",
              ")",
              "",
              "var barnmbnvtiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak per 31.12\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnmutplan, barnmbnvtiltak) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med tiltaksplan av barn med hjelpetiltak (prosent)",
            "expression": [
              "",
              "",
              "var barnmtiltplan = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med hjelpetiltak 31.12. med tiltaksplan\")",
              ")",
              "",
              "var barnmhjtiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med hjelpetiltak per 31.12.\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnmtiltplan, barnmhjtiltak) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med omsorgsplan av barn under omsorg (prosent)",
            "expression": [
              "",
              "",
              "var barnmomsplan = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med omsorgstiltak 31.12. med omsorgsplan\")",
              ")",
              "",
              "var barnmomstiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV03\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med omsorgstiltak per 31.12.\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(barnmomsplan, barnmomstiltak) * 100,",
              "        2",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BHG Ressursbruksindikator. Barnehager*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Barnehage\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "BNV Ressursbruksindikator. Barnevern*",
            "expression": [
              "",
              "",
              "var rbi = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Barnevern\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "GRS Ressursbruksindikator. Grunnskole F202*",
            "expression": [
              "",
              "",
              "var rbi = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Grunnskole F202\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "GRS Ressursbruksindikator. Grunnskole*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Grunnskole\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "KHT Ressursbruksindikator. Kommunehelse*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Kommunehelse\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "PLO Ressursbruksindikator. Pleie og omsorg*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Pleie og omsorg\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "SOS Ressursbruksindikator. Sosiale tjenester*",
            "expression": [
              "",
              "",
              "var rbi =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"RBI01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Ressursbruksindikator(uveid snitt)\"),",
              "    FILTER(ALL(Nettverk[Nettverknavn]), [Nettverknavn] = \"Sosialtjenesten\")",
              ")",
              "",
              "return (",
              "    ROUND(rbi, 3)",
              ")"
            ],
            "displayFolder": "Sosiale tjenester"
          },
          {
            "name": "KHT Årsverk ergoterapeuter per 10 000 innbyggere uADM",
            "expression": [
              "",
              "",
              "/* totalt årsverk */",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer i alt\"",
              "    )",
              ")",
              "",
              "/* Funksjon 120 */",
              "var admin = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Administrasjon (f120)\"",
              "    )",
              ")",
              "",
              "/* totale befolkning */",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(aarsverk) || ISBLANK(admin)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(aarsverk - admin, bef) * 10000 , ",
              "            1 ",
              "        )",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "KHT Årsverk ergoterapeuter nov2019",
            "expression": [
              "",
              "",
              "/* totalt årsverk */",
              "var f233 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Annet forebyggende helsearbeid (f233) - Annet forebyggende arbeid\"",
              "    )",
              ")",
              "",
              "/* Funksjon 120 */",
              "var f241 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Diagnose/ behandling, re-/habilitering (f241)\"",
              "    )",
              ")",
              "",
              "var f232 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk ergoteraputer. Forebygging, helsestasjons- og skolehelsetjeneste (f232)\"",
              "    )",
              ")",
              "",
              "/* totale befolkning */",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\")",
              ")",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(f233) || ISBLANK(f241) || ISBLANK(f232)",
              "",
              "return (  ",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE(f233 + f241 + f232, DIVIDE(bef, 10000)) , ",
              "            1 ",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "PLO Utgifter per oppholdsdøgn i institusjon",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12209\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Utgifter per oppholdsdøgn i institusjon (kr)\"",
              "    )",
              ")"
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "PLO Andel brukere av hjemmetjenester av befolkningen 0-66 år",
            "expression": [
              "",
              "",
              "var brukere = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12292\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Hjemmetjenester - brukere 0-66 år (antall)\"",
              "    )",
              ")",
              "",
              "var innb =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Personer (antall)\"",
              "    ),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = ",
              "        \"0 - 66 år\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(brukere, innb) * 100,",
              "        3",
              "    )",
              ")",
              ""
            ],
            "displayFolder": "Pleie og omsorg"
          },
          {
            "name": "EIE Tilstandsvurdering grunnskole (prosent)",
            "expression": [
              "",
              "",
              "var tilst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"EIE01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Tilstandsvurdering grunnskole (prosent)\")",
              ")",
              "",
              "return (",
              "    ROUND(tilst, 2)",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "EIE Tilstandsvurdering pleie og omsorg (prosent)",
            "expression": [
              "",
              "",
              "var tilst =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"EIE01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Tilstandsvurdering pleie og omsorg (prosent)\")",
              ")",
              "",
              "return (",
              "    ROUND(tilst, 2)",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "KHT Årsverk skolehelsetjenesten totalt per 1 000 innbyggere 6-20 år",
            "expression": [
              "",
              "",
              "var aarsverk = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk totalt skolehelsetjenesten uten ledelse\"",
              "    )",
              ")",
              "",
              "var bef = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"), ",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"6-20 år\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(aarsverk, DIVIDE(bef, 1000)),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "GRS Elever i kommunale og private grunnskoler med spesialundervisning, 8.-10. trinn (prosent)",
            "expression": [
              "",
              "",
              "var spes = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler som får spesialundervisning  (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"8.-10. trinn\") ",
              ")",
              "",
              "var elev = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12222\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Elever i kommunale og private grunnskoler (antall)\"",
              "    ),",
              "    FILTER(ALL('Årstrinn'[Årstrinnnavn]), [Årstrinnnavn] = \"8.-10. trinn\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(spes, elev) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Grunnskole"
          },
          {
            "name": "BHG Foreldretilfredshet barnehage*",
            "expression": [
              "",
              "",
              "var resultat =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BHG02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Foreldreundersøkelsen: Tilfredshet\")",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        resultat,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnehage"
          },
          {
            "name": "EIE Snitt årlig investering per innbygger siste fire år",
            "expression": [
              "",
              "",
              "/* Hvilket år brukereren velger endrer denne */",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "/* aar variablene er kommunens brutto investeringsutgifter på funksjon/tjenesteområde på formålsbygg*/",
              "var aar1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 3)",
              ")",
              "",
              "var aar2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 2)",
              ")",
              "",
              "var aar3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 1)",
              ")",
              "",
              "var aar4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12559\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK6\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar)",
              ")",
              "",
              "/* bef variablene er befolkningen i kommunen */",
              "var bef1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 3)",
              ")",
              "",
              "var bef2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 2)",
              ")",
              "",
              "var bef3 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 1)",
              ")",
              "",
              "var bef4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"I alt\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar)",
              ")",
              "",
              "/* indeks variablene er byggekostnadsindeksen for det gitte året */",
              "var indeks1 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"08655\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Byggjekostnadsindeks\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 3)",
              ")",
              "",
              "var indeks2 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"08655\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Byggjekostnadsindeks\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 2)",
              ")",
              "",
              "var indeks3 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"08655\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Byggjekostnadsindeks\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar - 1)",
              ")",
              "",
              "var indeks4 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"08655\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Byggjekostnadsindeks\"),",
              "    FILTER(ALL('År'[År]), [År] = valgte_aar)",
              ")",
              "",
              "var indeks1div =",
              "DIVIDE(indeks4, indeks1)",
              "",
              "var indeks2div =",
              "DIVIDE(indeks4, indeks2)",
              "",
              "var indeks3div =",
              "DIVIDE(indeks4, indeks3)",
              "",
              "var indeks4div =",
              "DIVIDE(indeks4, indeks4)",
              "",
              "/* ganger brutto drift for gitte året med indeks og deler dette på befolkningen */",
              "var aar1bef1 = ",
              "DIVIDE(aar1 * indeks1div, bef1)",
              "",
              "var aar2bef2 = ",
              "DIVIDE(aar2 * indeks2div, bef2)",
              "",
              "var aar3bef3 = ",
              "DIVIDE(aar3 * indeks3div, bef3)",
              "",
              "var aar4bef4 = ",
              "DIVIDE(aar4 * indeks4div, bef4)",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(aar1) || ISBLANK(aar2) || ISBLANK(aar3) || ISBLANK(aar4) ||",
              "ISBLANK(aar1bef1) || ISBLANK(aar2bef2) || ISBLANK(aar3bef3) || ISBLANK(aar4bef4)",
              "",
              "return (",
              "    ROUND(",
              "        /* snitt verdien av alle 4 årene */",
              "        DIVIDE(aar1bef1 + aar2bef2 + aar3bef3 + aar4bef4, 4) * 1000,",
              "            0",
              "    )",
              ")"
            ],
            "displayFolder": "Eiendomsforvaltning"
          },
          {
            "name": "BNV Netto driftsutgifter barnevernstjenester per innbygger 0-24 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrbv = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD2\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"244\", \"251\", \"252\"}),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var barn = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0-17 år\",",
              "        \"18-24 år\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE((ndrbv*1000), barn),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med barneverntiltak i forhold til innbyggere 0-24 år (prosent)",
            "expression": [
              "",
              "",
              "/* Valg mellom i løpet av året eller per 31.12 */",
              "var barn_mtiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN  {",
              "        \"0-22 år\",",
              "        \"0-24 år\"",
              "    }),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "var pers_024 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn]= \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0-17 år\",",
              "        \"18-24 år\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(    ",
              "        DIVIDE(barn_mtiltak, pers_024) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn som er plassert i løpet av året i prosent av antall innbyggere 0-24 år",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var barn_024 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0-17 år\",",
              "        \"18-24 år\"",
              "    })",
              ")",
              "",
              "var formel_022 =",
              "DIVIDE(",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)], ",
              "    barn_024",
              ") * 100",
              "",
              "var formel_024 =",
              "DIVIDE(",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-24 år som er plassert f252 (antall)], ",
              "    barn_024",
              ") * 100",
              "",
              "return (",
              "    ROUND(",
              "        IF(valgte_aar >= 2021, formel_024, formel_022),",
              "        2",
              "        )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn som ikke er plassert i løpet av året i prosent av alle i tiltak (0-24 år)",
            "expression": [
              "",
              "",
              "var valgte_aar = SELECTEDVALUE('År'[År])",
              "",
              "var tiltak = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med barnevernstiltak i løpet av året  (antall)\"",
              "    ),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0-22 år\",",
              "        \"0-24 år\"",
              "    }),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = \"Tiltak i alt\")",
              ")",
              "",
              "var formel_022 =",
              "DIVIDE(",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)],",
              "    tiltak",
              ") * 100",
              "",
              "var formel_024 =",
              "DIVIDE(",
              "    [BNV Barn med barnevernstiltak i løpet av året 0-24 år som ikke er plassert f251 (antall)],",
              "    tiltak",
              ") * 100 ",
              "",
              "return (",
              "    ROUND(",
              "        IF(valgte_aar >= 2021, formel_024, formel_022),",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Andel barn med tiltak 0-5 år av antall innbyggere 0-5 år (prosent)",
            "expression": [
              "",
              "",
              "var tiltak_05 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"BNV02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Tiltak i alt\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \" 0 - 5 år\")",
              ")",
              "",
              "var barn_05 = ",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11805\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Personer (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0-5 år\"",
              "    })",
              ")",
              "",
              "return (",
              "    ROUND(",
              "        DIVIDE(tiltak_05, barn_05) * 100,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-24 år som ikke er plassert f251 (antall)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall)\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-24 år\"),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = ",
              "        \"251 - Barnevernstiltak når barnet ikke er plassert av barnevernet\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Barn med barnevernstiltak i løpet av året 0-24 år som er plassert f252 (antall)",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12275\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med barnevernstiltak i løpet av året  (antall)\"",
              "    ),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] = \"0-24 år\"),",
              "    FILTER(ALL(Funksjon[Funksjonnavn]), [Funksjonnavn] = ",
              "        \"252 - Barnevernstiltak når barnet er plassert av barnevernet\"",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "BNV Brutto driftsutgifter per barn (f244) med undersøkelse eller tiltak (kroner)",
            "expression": [
              "",
              "",
              "var tiltak =",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12870\"),",
              "    FILTER(ALL(Alder[Aldernavn]), [Aldernavn] IN {",
              "        \"0-22 år\",",
              "        \"0-24 år\"",
              "    }),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Barn med undersøkelse og/eller tiltak i løpet av året (antall)\"",
              "    )",
              ")",
              "",
              "var brutto244 =",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12367\"),",
              "    FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"244\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(brutto244 * 1000, tiltak)",
              "",
              "return (",
              "    ROUND(",
              "        formel,",
              "        1",
              "    )",
              ")"
            ],
            "displayFolder": "Barnevern"
          },
          {
            "name": "KHT Målt produksjon helsestasjon 2022-vektinger",
            "expression": [
              "",
              "",
              "var undGrav = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13533\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall nyinnskrevne gravide som har møtt til svangerskapskontroll (antall)\"",
              "    )",
              ")",
              "",
              "var undFG = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = ",
              "        \"Hjemmebesøk av helsesykepleier til nyfødte\"",
              "    )",
              ")",
              "",
              "var und8 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt 8.leveuke\")",
              ")",
              "",
              "var und23 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt ved 2-års alder\")",
              ")",
              "",
              "var und4 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Undersøkt ved 4-års alder\")",
              ")",
              "",
              "var hjem = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11993\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Barn (antall)\"),",
              "    FILTER(ALL(Helsekontroller[Helsekontrollernavn]), [Helsekontrollernavn] = \"Hjemmebesøk av jordmor innen tre døgn etter hjemkomst\")",
              ")",
              "",
              "var arsverkhst05 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"KHT02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsverk 0-5 totalt uten ledelse. Helsestasjon 0-5 år\"",
              "    )",
              ")",
              "",
              "/* Returnerer true hvis en av verdiene er blanke */",
              "",
              "var vekthstprod = ",
              "(0.15*undGrav)+(0.24*undFG)+(0.24*hjem)+(0.12*und8)+(0.13*und23)+(0.12*und4)",
              "",
              "var resultat =",
              "DIVIDE(vekthstprod, arsverkhst05)",
              "",
              "var har_blanke_verdier =",
              "ISBLANK(undGrav) || ISBLANK(undFG) || ISBLANK(und8) || ISBLANK(und23) || ISBLANK(und4) || ",
              "    ISBLANK(arsverkhst05) || ISBLANK(hjem)",
              "",
              "return (",
              "    IF(har_blanke_verdier,",
              "        BLANK(),",
              "        ROUND(",
              "            resultat,",
              "            1",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Kommunehelse"
          },
          {
            "name": "VAR Gebyrgrunnlag per innbygger (vann)",
            "expression": [
              "",
              "",
              "var gebyr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13056\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Vann\"),",
              "    FILTER(ALL('Post'[Postnavn]), [Postnavn] = \"Gebyrgrunnlag\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13143\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall innbyggere tilknyttet kommunal vannforsyning (antall)\"",
              "    )",
              ")",
              "",
              "var formel =",
              "DIVIDE(gebyr, innb) * 1000",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Årsgebyr ekskl. mva for standard bolig på 120 m² (kroner) (vann)",
            "expression": [
              "",
              "",
              "var gebyr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12842\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsgebyr for vannforsyning - ekskl. mva. (kr)\"",
              "    )",
              ")",
              "",
              "return (",
              "    gebyr",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Hygienisk betryggende drikkevann (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Hygienisk betryggende drikkevann\"",
              "    )",
              ")",
              "",
              "return (",
              "    kvalitetsindeks",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Bruksmessig vannkvalitet (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Bruksmessig vannkvalitet\"",
              "    )",
              ")",
              "",
              "return (",
              "    kvalitetsindeks",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Leveringsstabilitet (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Leveringsstabilitet\"",
              "    )",
              ")",
              "",
              "return (",
              "    kvalitetsindeks",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Alternativ forsyning (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR01\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Alternativ forsyning\"",
              "    )",
              ")",
              "",
              "return (",
              "    kvalitetsindeks",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Ledningsnettets funksjon (kvalitetsindeks) (vann)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR01\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Vann\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Ledningsnettets funksjon\"",
              "    )",
              ")",
              "",
              "return (",
              "    kvalitetsindeks",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Vektet kvalitetsindeks (KI) (vann)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR01\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Vann\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Vektet kvalitetsindeks (KI)\"",
              "    )",
              ")",
              "",
              "return (",
              "    kvalitetsindeks",
              ")"
            ],
            "displayFolder": "VAR\\Vann"
          },
          {
            "name": "VAR Gebyrgrunnlag per innbygger (avløp)",
            "expression": [
              "",
              "",
              "var gebyr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13056\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Avløp\"),",
              "    FILTER(ALL('Post'[Postnavn]), [Postnavn] = \"Gebyrgrunnlag\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13144\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Antall innbyggere tilknyttet kommunalt avløp (=>50 pe) (antall)\"",
              "    )",
              ")",
              "",
              "var formel =",
              "DIVIDE(gebyr, innb) * 1000",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Overholdelse gjeldende rensekrav (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Overholdelse gjeldende rensekrav\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Tilknytning til godkjent utslipp (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Tilknytning til godkjent utslipp\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Kvalitet og bruk av slam (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Kvalitet og bruk av slam\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Overløpsutslipp fra avløpsnettet (kvalitetsindeks)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR02\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Overløpsutslipp fra avløpsnettet\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Ledningsnettets funksjon (kvalitetsindeks) (avløp)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR02\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Avløp\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Ledningsnettets funksjon\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Vektet kvalitetsindeks (KI) (avløp)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"VAR02\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Avløp\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Vektet kvalitetsindeks (KI)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Gebyrgrunnlag per innbygger (renovasjon)",
            "expression": [
              "",
              "",
              "var gebyr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13056\"),",
              "    FILTER(ALL('Tjenesteområde'[Tjenesteområdenavn]), [Tjenesteområdenavn] = \"Avfall\"),",
              "    FILTER(ALL('Post'[Postnavn]), [Postnavn] = \"Gebyrgrunnlag\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"11820\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "var formel =",
              "DIVIDE(gebyr, innb) * 1000",
              "",
              "return (",
              "    ROUND(formel, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Renovasjon"
          },
          {
            "name": "VAR Mengde husholdningsavfall (kg per innbygger)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12263\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Husholdningsavfall per årsinnbygger (kg)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Renovasjon"
          },
          {
            "name": "VAR Årsgebyr ekskl. mva for standard bolig på 120 m² (kroner) (avløp)",
            "expression": [
              "",
              "",
              "var gebyr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12842\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsgebyr for avløpstjenesten - ekskl. mva. (kr)\"",
              "    )",
              ")",
              "",
              "return (",
              "    gebyr",
              ")"
            ],
            "displayFolder": "VAR\\Avløp"
          },
          {
            "name": "VAR Årsgebyr ekskl. mva for standard bolig på 120 m² (kroner) (renovasjon)",
            "expression": [
              "",
              "",
              "var gebyr = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12842\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Årsgebyr for avfallstjenesten - ekskl. mva. (kr)\"",
              "    )",
              ")",
              "",
              "return (",
              "    gebyr",
              ")"
            ],
            "displayFolder": "VAR\\Renovasjon"
          },
          {
            "name": "VAR Andel levert til materialgjenvinning (prosent av total avfallsmengde)",
            "expression": [
              "",
              "",
              "var kvalitetsindeks = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12263\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = ",
              "        \"Andel levert til materialgjenvinning inkl. biologisk behandling (prosent)\"",
              "    )",
              ")",
              "",
              "return (",
              "    ROUND(kvalitetsindeks, 2)",
              ")"
            ],
            "displayFolder": "VAR\\Renovasjon"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ASSS Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>149</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>184</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <int>147</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Grunnskole</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>VAR</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Grunnskole</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>VAR</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Pleie og omsorg</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Andre</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Byggesak</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eiendomsforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kommunehelse</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Sosiale tjenester</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Grunnskole</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>VAR</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Energitype",
        "columns": [
          {
            "name": "Energitypekode",
            "dataType": "string",
            "sourceColumn": "Energitypekode"
          },
          {
            "name": "Energitypenavn",
            "dataType": "string",
            "sourceColumn": "Energitypenavn"
          },
          {
            "name": "EnergitypekodeNavn",
            "dataType": "string",
            "sourceColumn": "EnergitypekodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Energitype",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EnergitypekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>184</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EnergitypekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EnergitypekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Energitype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EnergitypekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>184</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EnergitypekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypenavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EnergitypekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Funksjonnavn",
            "dataType": "string",
            "sourceColumn": "Funksjonnavn"
          },
          {
            "name": "FunksjonkodeNavn",
            "dataType": "string",
            "sourceColumn": "FunksjonkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Funksjon",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FunksjonkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>173</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FunksjonkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>FunksjonkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Funksjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FunksjonkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>173</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FunksjonkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>FunksjonkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "ASSS kommune",
            "dataType": "string",
            "sourceColumn": "ASSS kommune"
          }
        ],
        "partitions": [
          {
            "name": "Region",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Navn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>75</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KodeNummernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>170</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regionnummer</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ASSS kommune</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>153</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigFraDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>139</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigTilDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>135</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Navn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KodeNummernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regionnummer</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kategori</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ASSS kommune</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigFraDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GyldigTilDato</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>ASSS kommune</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Navn</string>",
              "      </key>",
              "      <value>",
              "        <int>75</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KodeNummernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>170</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regionnummer</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kategori</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ASSS kommune</string>",
              "      </key>",
              "      <value>",
              "        <int>153</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigFraDato</string>",
              "      </key>",
              "      <value>",
              "        <int>139</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigTilDato</string>",
              "      </key>",
              "      <value>",
              "        <int>135</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Navn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KodeNummernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regionnummer</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kategori</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ASSS kommune</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigFraDato</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GyldigTilDato</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>ASSS kommune</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Kilde",
            "dataType": "string",
            "sourceColumn": "Kilde"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellnummer</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>116</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TabellNummerNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>180</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Gruppe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellnummer</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TabellNummerNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Gruppe</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilde</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Gruppe</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kilde</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabellnummer</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>116</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TabellNummerNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>180</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Gruppe</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilde</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabellnummer</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TabellNummerNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Gruppe</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilde</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Gruppe</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kilde</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Årstall",
            "dataType": "string",
            "sourceColumn": "Årstall"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstall</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>138</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstall</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstall</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstall</string>",
              "      </key>",
              "      <value>",
              "        <int>138</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstall</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Årstall</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Alle Data",
        "isHidden": true,
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Energitypekode",
            "dataType": "string",
            "sourceColumn": "Energitypekode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Handsamingstidkode",
            "dataType": "string",
            "sourceColumn": "Handsamingstidkode"
          },
          {
            "name": "Tiltakskategorikode",
            "dataType": "string",
            "sourceColumn": "Tiltakskategorikode"
          },
          {
            "name": "Alderkode",
            "dataType": "string",
            "sourceColumn": "Alderkode"
          },
          {
            "name": "Tjenestegrupperkode",
            "dataType": "string",
            "sourceColumn": "Tjenestegrupperkode"
          },
          {
            "name": "Utdanningkode",
            "dataType": "string",
            "sourceColumn": "Utdanningkode"
          },
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "Avtaleformkode",
            "dataType": "string",
            "sourceColumn": "Avtaleformkode"
          },
          {
            "name": "Helsekontrollerkode",
            "dataType": "string",
            "sourceColumn": "Helsekontrollerkode"
          },
          {
            "name": "Eieformkode",
            "dataType": "string",
            "sourceColumn": "Eieformkode"
          },
          {
            "name": "Årstrinnkode",
            "dataType": "string",
            "sourceColumn": "Årstrinnkode"
          },
          {
            "name": "Eierforholdkode",
            "dataType": "string",
            "sourceColumn": "Eierforholdkode"
          },
          {
            "name": "Oppholdstidkode",
            "dataType": "string",
            "sourceColumn": "Oppholdstidkode"
          },
          {
            "name": "Kjønnkode",
            "dataType": "string",
            "sourceColumn": "Kjønnkode"
          },
          {
            "name": "Stillingstypekode",
            "dataType": "string",
            "sourceColumn": "Stillingstypekode"
          },
          {
            "name": "Kompetansekode",
            "dataType": "string",
            "sourceColumn": "Kompetansekode"
          },
          {
            "name": "Kildekode",
            "dataType": "string",
            "sourceColumn": "Kildekode"
          },
          {
            "name": "Tjenesteområdekode",
            "dataType": "string",
            "sourceColumn": "Tjenesteområdekode"
          },
          {
            "name": "Nettverkkode",
            "dataType": "string",
            "sourceColumn": "Nettverkkode"
          },
          {
            "name": "Lærerkompetansekode",
            "dataType": "string",
            "sourceColumn": "Lærerkompetansekode"
          },
          {
            "name": "Konklusjon på meldingakode",
            "dataType": "string",
            "sourceColumn": "Konklusjon på meldingakode"
          },
          {
            "name": "Konklusjon på undersøking avsluttakode",
            "dataType": "string",
            "sourceColumn": "Konklusjon på undersøking avsluttakode"
          },
          {
            "name": " omsorgs-/hjelpetiltakkode",
            "dataType": "string",
            "sourceColumn": " omsorgs-/hjelpetiltakkode"
          },
          {
            "name": "Personellets utdanningkode",
            "dataType": "string",
            "sourceColumn": "Personellets utdanningkode"
          },
          {
            "name": "Handsamingstid av meldingakode",
            "dataType": "string",
            "sourceColumn": "Handsamingstid av meldingakode"
          },
          {
            "name": "Stillingkode",
            "dataType": "string",
            "sourceColumn": "Stillingkode"
          },
          {
            "name": "Postkode",
            "dataType": "string",
            "sourceColumn": "Postkode"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>156</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>78</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>187</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>222</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>189</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>164</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverkkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>140</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Personellets utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>162</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>188</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>83</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Postkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>136</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>29</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>28</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>27</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverkkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>25</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>26</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Personellets utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>30</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>31</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>32</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Postkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>33</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverkkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Personellets utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Postkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>156</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>78</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <int>187</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakode</string>",
              "      </key>",
              "      <value>",
              "        <int>222</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>189</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>164</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nettverkkode</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>140</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Personellets utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>162</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>188</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingkode</string>",
              "      </key>",
              "      <value>",
              "        <int>83</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Postkode</string>",
              "      </key>",
              "      <value>",
              "        <int>136</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>29</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakode</string>",
              "      </key>",
              "      <value>",
              "        <int>28</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>27</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nettverkkode</string>",
              "      </key>",
              "      <value>",
              "        <int>25</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>26</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Personellets utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>30</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>31</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingkode</string>",
              "      </key>",
              "      <value>",
              "        <int>32</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Postkode</string>",
              "      </key>",
              "      <value>",
              "        <int>33</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nettverkkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Personellets utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Postkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Alder",
        "columns": [
          {
            "name": "Alderkode",
            "dataType": "string",
            "sourceColumn": "Alderkode"
          },
          {
            "name": "Aldernavn",
            "dataType": "string",
            "sourceColumn": "Aldernavn"
          },
          {
            "name": "AlderkodeNavn",
            "dataType": "string",
            "sourceColumn": "AlderkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Alder",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aldernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AlderkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>147</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aldernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AlderkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Alderkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Aldernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AlderkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alder].* FROM [dbo].[Alder] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alder"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aldernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AlderkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>147</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aldernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AlderkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Alderkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Aldernavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AlderkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Handsamingstid",
        "columns": [
          {
            "name": "Handsamingstidkode",
            "dataType": "string",
            "sourceColumn": "Handsamingstidkode"
          },
          {
            "name": "Handsamingstidnavn",
            "dataType": "string",
            "sourceColumn": "Handsamingstidnavn"
          },
          {
            "name": "HandsamingstidkodeNavn",
            "dataType": "string",
            "sourceColumn": "HandsamingstidkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Handsamingstid",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Handsamingstid].* FROM [dbo].[Handsamingstid] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>HandsamingstidkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>222</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>HandsamingstidkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>HandsamingstidkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Handsamingstid].* FROM [dbo].[Handsamingstid] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Handsamingstid"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>HandsamingstidkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>222</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>HandsamingstidkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>HandsamingstidkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Kilde",
        "columns": [
          {
            "name": "Kildekode",
            "dataType": "string",
            "sourceColumn": "Kildekode"
          },
          {
            "name": "Kildenavn",
            "dataType": "string",
            "sourceColumn": "Kildenavn"
          },
          {
            "name": "KildekodeNavn",
            "dataType": "string",
            "sourceColumn": "KildekodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Kilde",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Kilde].* FROM [dbo].[Kilde] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KildekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>143</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KildekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kildenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KildekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kilde].* FROM [dbo].[Kilde] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kilde"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KildekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>143</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KildekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Kildekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kildenavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KildekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Omsorgs-hjelpetiltak",
        "columns": [
          {
            "name": " omsorgs-/hjelpetiltakkode",
            "dataType": "string",
            "sourceColumn": " omsorgs-/hjelpetiltakkode"
          },
          {
            "name": " omsorgs-/hjelpetiltaknavn",
            "dataType": "string",
            "sourceColumn": " omsorgs-/hjelpetiltaknavn"
          },
          {
            "name": " omsorgs-/hjelpetiltakkodeNavn",
            "dataType": "string",
            "sourceColumn": " omsorgs-/hjelpetiltakkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Omsorgs-hjelpetiltak",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Omsorgs-/hjelpetiltak].* FROM [dbo].[Omsorgs-/hjelpetiltak] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>181</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltaknavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>157</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>156</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltaknavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltaknavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string> omsorgs-/hjelpetiltakkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Omsorgs-/hjelpetiltak].* FROM [dbo].[Omsorgs-/hjelpetiltak] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Omsorgs-/hjelpetiltak"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>181</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltaknavn</string>",
              "      </key>",
              "      <value>",
              "        <int>157</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>156</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltaknavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltaknavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string> omsorgs-/hjelpetiltakkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tiltakskategori",
        "columns": [
          {
            "name": "Tiltakskategorikode",
            "dataType": "string",
            "sourceColumn": "Tiltakskategorikode"
          },
          {
            "name": "Tiltakskategorinavn",
            "dataType": "string",
            "sourceColumn": "Tiltakskategorinavn"
          },
          {
            "name": "TiltakskategorikodeNavn",
            "dataType": "string",
            "sourceColumn": "TiltakskategorikodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Tiltakskategori",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Tiltakskategori].* FROM [dbo].[Tiltakskategori] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorinavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TiltakskategorikodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>212</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorinavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TiltakskategorikodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorinavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TiltakskategorikodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tiltakskategori].* FROM [dbo].[Tiltakskategori] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tiltakskategori"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorinavn</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TiltakskategorikodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>212</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorinavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TiltakskategorikodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorinavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TiltakskategorikodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tjenestegrupper",
        "columns": [
          {
            "name": "Tjenestegrupperkode",
            "dataType": "string",
            "sourceColumn": "Tjenestegrupperkode"
          },
          {
            "name": "Tjenestegruppernavn",
            "dataType": "string",
            "sourceColumn": "Tjenestegruppernavn"
          },
          {
            "name": "TjenestegrupperkodeNavn",
            "dataType": "string",
            "sourceColumn": "TjenestegrupperkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Tjenestegrupper",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Tjenestegrupper].* FROM [dbo].[Tjenestegrupper] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>189</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegruppernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>189</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TjenestegrupperkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>225</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegruppernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TjenestegrupperkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegrupperkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenestegruppernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TjenestegrupperkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tjenestegrupper].* FROM [dbo].[Tjenestegrupper] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tjenestegrupper"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>189</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegruppernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>189</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TjenestegrupperkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>225</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegruppernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TjenestegrupperkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegrupperkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenestegruppernavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TjenestegrupperkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Utdanning",
        "columns": [
          {
            "name": "Utdanningkode",
            "dataType": "string",
            "sourceColumn": "Utdanningkode"
          },
          {
            "name": "Utdanningnavn",
            "dataType": "string",
            "sourceColumn": "Utdanningnavn"
          },
          {
            "name": "UtdanningkodeNavn",
            "dataType": "string",
            "sourceColumn": "UtdanningkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Utdanning",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Utdanning].* FROM [dbo].[Utdanning] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>146</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UtdanningkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>182</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UtdanningkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Utdanningnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>UtdanningkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Utdanning].* FROM [dbo].[Utdanning] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Utdanning"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>146</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UtdanningkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UtdanningkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Utdanningnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>UtdanningkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Regnskapsbegrep",
        "columns": [
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "Regnskapsbegrepnavn",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepnavn"
          },
          {
            "name": "RegnskapsbegrepkodeNavn",
            "dataType": "string",
            "sourceColumn": "RegnskapsbegrepkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Regnskapsbegrep",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Regnskapsbegrep].* FROM [dbo].[Regnskapsbegrep] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RegnskapsbegrepkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>233</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RegnskapsbegrepkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Regnskapsbegrepnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RegnskapsbegrepkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Regnskapsbegrep].* FROM [dbo].[Regnskapsbegrep] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Regnskapsbegrep"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RegnskapsbegrepkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>233</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RegnskapsbegrepkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Regnskapsbegrepnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RegnskapsbegrepkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Avtaleform",
        "columns": [
          {
            "name": "Avtaleformkode",
            "dataType": "string",
            "sourceColumn": "Avtaleformkode"
          },
          {
            "name": "Avtaleformnavn",
            "dataType": "string",
            "sourceColumn": "Avtaleformnavn"
          },
          {
            "name": "AvtaleformkodeNavn",
            "dataType": "string",
            "sourceColumn": "AvtaleformkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Avtaleform",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Avtaleform].* FROM [dbo].[Avtaleform] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AvtaleformkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>187</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>145</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>81</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AvtaleformkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Avtaleformnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AvtaleformkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Avtaleform].* FROM [dbo].[Avtaleform] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Avtaleform"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AvtaleformkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>187</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>145</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>81</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AvtaleformkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Avtaleformnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AvtaleformkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Helsekontroller",
        "columns": [
          {
            "name": "Helsekontrollerkode",
            "dataType": "string",
            "sourceColumn": "Helsekontrollerkode"
          },
          {
            "name": "Helsekontrollernavn",
            "dataType": "string",
            "sourceColumn": "Helsekontrollernavn"
          },
          {
            "name": "HelsekontrollerkodeNavn",
            "dataType": "string",
            "sourceColumn": "HelsekontrollerkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Helsekontroller",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Helsekontroller].* FROM [dbo].[Helsekontroller] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>179</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>HelsekontrollerkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>215</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>HelsekontrollerkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollerkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Helsekontrollernavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>HelsekontrollerkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Helsekontroller].* FROM [dbo].[Helsekontroller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Helsekontroller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>179</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>HelsekontrollerkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>215</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollernavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>HelsekontrollerkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollerkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Helsekontrollernavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>HelsekontrollerkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Eieform",
        "columns": [
          {
            "name": "Eieformkode",
            "dataType": "string",
            "sourceColumn": "Eieformkode"
          },
          {
            "name": "Eieformnavn",
            "dataType": "string",
            "sourceColumn": "Eieformnavn"
          },
          {
            "name": "EieformkodeNavn",
            "dataType": "string",
            "sourceColumn": "EieformkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Eieform",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Eieform].* FROM [dbo].[Eieform] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>128</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EieformkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>164</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EieformkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eieformnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EieformkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Eieform].* FROM [dbo].[Eieform] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Eieform"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>128</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EieformkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>164</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EieformkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Eieformkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eieformnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EieformkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Årstrinn",
        "columns": [
          {
            "name": "Årstrinnkode",
            "dataType": "string",
            "sourceColumn": "Årstrinnkode"
          },
          {
            "name": "Årstrinnnavn",
            "dataType": "string",
            "sourceColumn": "Årstrinnnavn"
          },
          {
            "name": "ÅrstrinnkodeNavn",
            "dataType": "string",
            "sourceColumn": "ÅrstrinnkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Årstrinn",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Årstrinn].* FROM [dbo].[Årstrinn] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>130</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ÅrstrinnkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>166</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ÅrstrinnkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Årstrinnnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ÅrstrinnkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Årstrinn].* FROM [dbo].[Årstrinn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Årstrinn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>130</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ÅrstrinnkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>166</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ÅrstrinnkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Årstrinnnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ÅrstrinnkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Eierforhold",
        "columns": [
          {
            "name": "Eierforholdkode",
            "dataType": "string",
            "sourceColumn": "Eierforholdkode"
          },
          {
            "name": "Eierforholdnavn",
            "dataType": "string",
            "sourceColumn": "Eierforholdnavn"
          },
          {
            "name": "EierforholdkodeNavn",
            "dataType": "string",
            "sourceColumn": "EierforholdkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Eierforhold",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Eierforhold].* FROM [dbo].[Eierforhold] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EierforholdkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>187</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EierforholdkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Eierforholdnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>EierforholdkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Eierforhold].* FROM [dbo].[Eierforhold] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Eierforhold"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EierforholdkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>187</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EierforholdkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Eierforholdnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>EierforholdkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Oppholdstid",
        "columns": [
          {
            "name": "Oppholdstidkode",
            "dataType": "string",
            "sourceColumn": "Oppholdstidkode"
          },
          {
            "name": "Oppholdstidnavn",
            "dataType": "string",
            "sourceColumn": "Oppholdstidnavn"
          },
          {
            "name": "OppholdstidkodeNavn",
            "dataType": "string",
            "sourceColumn": "OppholdstidkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Oppholdstid",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Oppholdstid].* FROM [dbo].[Oppholdstid] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OppholdstidkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>195</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OppholdstidkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Oppholdstidnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>OppholdstidkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Oppholdstid].* FROM [dbo].[Oppholdstid] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Oppholdstid"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OppholdstidkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>195</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OppholdstidkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Oppholdstidnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>OppholdstidkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Kjønn",
        "columns": [
          {
            "name": "Kjønnkode",
            "dataType": "string",
            "sourceColumn": "Kjønnkode"
          },
          {
            "name": "Kjønnnavn",
            "dataType": "string",
            "sourceColumn": "Kjønnnavn"
          },
          {
            "name": "KjønnkodeNavn",
            "dataType": "string",
            "sourceColumn": "KjønnkodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Kjønn",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>114</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KjønnkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>150</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KjønnkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kjønnnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KjønnkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kjønn].* FROM [dbo].[Kjønn] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kjønn"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>114</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KjønnkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>150</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KjønnkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kjønnnavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KjønnkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Stillingstype",
        "columns": [
          {
            "name": "Stillingstypekode",
            "dataType": "string",
            "sourceColumn": "Stillingstypekode"
          },
          {
            "name": "Stillingstypenavn",
            "dataType": "string",
            "sourceColumn": "Stillingstypenavn"
          },
          {
            "name": "StillingstypekodeNavn",
            "dataType": "string",
            "sourceColumn": "StillingstypekodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Stillingstype",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Stillingstype].* FROM [dbo].[Stillingstype] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StillingstypekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>194</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StillingstypekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingstypenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StillingstypekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Stillingstype].* FROM [dbo].[Stillingstype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Stillingstype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StillingstypekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>194</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StillingstypekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingstypenavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StillingstypekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Kompetanse",
        "columns": [
          {
            "name": "Kompetansekode",
            "dataType": "string",
            "sourceColumn": "Kompetansekode"
          },
          {
            "name": "Kompetansenavn",
            "dataType": "string",
            "sourceColumn": "Kompetansenavn"
          },
          {
            "name": "KompetansekodeNavn",
            "dataType": "string",
            "sourceColumn": "KompetansekodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Kompetanse",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Kompetanse].* FROM [dbo].[Kompetanse] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>159</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KompetansekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>195</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KompetansekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kompetansenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>KompetansekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Kompetanse].* FROM [dbo].[Kompetanse] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Kompetanse"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>159</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KompetansekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>195</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KompetansekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kompetansenavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>KompetansekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tjenesteområde",
        "columns": [
          {
            "name": "Tjenesteområdekode",
            "dataType": "string",
            "sourceColumn": "Tjenesteområdekode"
          },
          {
            "name": "Tjenesteområdenavn",
            "dataType": "string",
            "sourceColumn": "Tjenesteområdenavn"
          },
          {
            "name": "TjenesteområdekodeNavn",
            "dataType": "string",
            "sourceColumn": "TjenesteområdekodeNavn"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Tjenesteområde",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Tjenesteområde].* FROM [dbo].[Tjenesteområde] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>187</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>187</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TjenesteområdekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>223</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TjenesteområdekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tjenesteområdenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TjenesteområdekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tjenesteområde].* FROM [dbo].[Tjenesteområde] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tjenesteområde"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <int>187</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>187</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TjenesteområdekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>223</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TjenesteområdekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tjenesteområdenavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TjenesteområdekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Nettverk",
        "columns": [
          {
            "name": "Nettverkkode",
            "dataType": "string",
            "sourceColumn": "Nettverkkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Nettverknavn",
            "dataType": "string",
            "sourceColumn": "Nettverknavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "NettverkkodeNavn",
            "dataType": "string",
            "sourceColumn": "NettverkkodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Nettverk",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Nettverk].* FROM [dbo].[Nettverk] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverkkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>178</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverknavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>178</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NettverkkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>228</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverkkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Nettverknavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>NettverkkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Nettverk].* FROM [dbo].[Nettverk] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Nettverk"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Nettverkkode</string>",
              "      </key>",
              "      <value>",
              "        <int>178</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nettverknavn</string>",
              "      </key>",
              "      <value>",
              "        <int>178</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NettverkkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>228</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Nettverkkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Nettverknavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>NettverkkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Lærerkompetanse",
        "columns": [
          {
            "name": "Lærerkompetansekode",
            "dataType": "string",
            "sourceColumn": "Lærerkompetansekode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Lærerkompetansenavn",
            "dataType": "string",
            "sourceColumn": "Lærerkompetansenavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "LærerkompetansekodeNavn",
            "dataType": "string",
            "sourceColumn": "LærerkompetansekodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Lærerkompetanse",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Lærerkompetanse].* FROM [dbo].[Lærerkompetanse] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>271</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>271</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LærerkompetansekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>321</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Lærerkompetansenavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>LærerkompetansekodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Lærerkompetanse].* FROM [dbo].[Lærerkompetanse] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Lærerkompetanse"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>271</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>271</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LærerkompetansekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>321</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansekode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Lærerkompetansenavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>LærerkompetansekodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Sammenslåtte Regioner",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "SammenslåingsDato",
            "dataType": "dateTime",
            "sourceColumn": "SammenslåingsDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Sammenslåtte Regioner",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Sammenslåtte Regioner].* FROM [dbo].[Sammenslåtte Regioner] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Sammenslåtte Regioner"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Handsamingstid av meldinga",
        "columns": [
          {
            "name": "Handsamingstid av meldingakode",
            "dataType": "string",
            "sourceColumn": "Handsamingstid av meldingakode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Handsamingstid av meldinganavn",
            "dataType": "string",
            "sourceColumn": "Handsamingstid av meldinganavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Handsamingstid av meldingakodeNavn",
            "dataType": "string",
            "sourceColumn": "Handsamingstid av meldingakodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Handsamingstid av meldinga",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Handsamingstid av meldinga].* FROM [dbo].[Handsamingstid av meldinga] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>374</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldinganavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>374</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>424</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldinganavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstid av meldingakodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Handsamingstid av meldinga].* FROM [dbo].[Handsamingstid av meldinga] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Handsamingstid av meldinga"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>374</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldinganavn</string>",
              "      </key>",
              "      <value>",
              "        <int>374</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>424</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldinganavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstid av meldingakodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Konklusjon på meldinga",
        "columns": [
          {
            "name": "Konklusjon på meldingakode",
            "dataType": "string",
            "sourceColumn": "Konklusjon på meldingakode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Konklusjon på meldinganavn",
            "dataType": "string",
            "sourceColumn": "Konklusjon på meldinganavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Konklusjon på meldingakodeNavn",
            "dataType": "string",
            "sourceColumn": "Konklusjon på meldingakodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Konklusjon på meldinga",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Konklusjon på meldinga].* FROM [dbo].[Konklusjon på meldinga] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>326</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldinganavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>326</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>376</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldinganavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på meldingakodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Konklusjon på meldinga].* FROM [dbo].[Konklusjon på meldinga] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Konklusjon på meldinga"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>326</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldinganavn</string>",
              "      </key>",
              "      <value>",
              "        <int>326</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>376</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldinganavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på meldingakodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Konklusjon på undersøking avslutta",
        "columns": [
          {
            "name": "Konklusjon på undersøking avsluttakode",
            "dataType": "string",
            "sourceColumn": "Konklusjon på undersøking avsluttakode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Konklusjon på undersøking avsluttanavn",
            "dataType": "string",
            "sourceColumn": "Konklusjon på undersøking avsluttanavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Konklusjon på undersøking avsluttakodeNavn",
            "dataType": "string",
            "sourceColumn": "Konklusjon på undersøking avsluttakodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Konklusjon på undersøking avslutta",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Konklusjon på undersøking avslutta].* FROM [dbo].[Konklusjon på undersøking avslutta] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>439</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttanavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>439</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>489</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttanavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjon på undersøking avsluttakodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Konklusjon på undersøking avslutta].* FROM [dbo].[Konklusjon på undersøking avslutta] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Konklusjon på undersøking avslutta"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakode</string>",
              "      </key>",
              "      <value>",
              "        <int>439</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttanavn</string>",
              "      </key>",
              "      <value>",
              "        <int>439</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>489</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttanavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjon på undersøking avsluttakodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Stilling",
        "columns": [
          {
            "name": "Stillingkode",
            "dataType": "string",
            "sourceColumn": "Stillingkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Stillingnavn",
            "dataType": "string",
            "sourceColumn": "Stillingnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "StillingkodeNavn",
            "dataType": "string",
            "sourceColumn": "StillingkodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Stilling",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Stilling].* FROM [dbo].[Stilling] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StillingkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>208</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>286</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>154</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Stillingnavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>StillingkodeNavn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabellkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Original dimensjonskode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Stilling].* FROM [dbo].[Stilling] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Stilling"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Stillingkode</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StillingkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>208</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>286</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>154</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Stillingkode</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Stillingnavn</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>StillingkodeNavn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tabellkode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Original dimensjonskode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Personellets utdanning",
        "columns": [
          {
            "name": "Personellets utdanningkode",
            "dataType": "string",
            "sourceColumn": "Personellets utdanningkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Personellets utdanningnavn",
            "dataType": "string",
            "sourceColumn": "Personellets utdanningnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Personellets utdanningkodeNavn",
            "dataType": "string",
            "sourceColumn": "Personellets utdanningkodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Personellets utdanning",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Personellets utdanning].* FROM [dbo].[Personellets utdanning] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Personellets utdanning].* FROM [dbo].[Personellets utdanning] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Personellets utdanning"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Post",
        "columns": [
          {
            "name": "Postkode",
            "dataType": "string",
            "sourceColumn": "Postkode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Postnavn",
            "dataType": "string",
            "sourceColumn": "Postnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "PostkodeNavn",
            "dataType": "string",
            "sourceColumn": "PostkodeNavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Post",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [dbo].[Post].* FROM [dbo].[Post] ",
              "dataSource": "VK-SXD0E-002;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Post].* FROM [dbo].[Post] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Post"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4e9f0201-a402-446a-8143-3524dec0a92e",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "664363a3-aadb-4475-b62b-318ab1c5d07f",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "babf348a-b5f1-43e9-b8c8-f41795230b5a",
        "fromTable": "Alle Data",
        "fromColumn": "Alderkode",
        "toTable": "Alder",
        "toColumn": "Alderkode"
      },
      {
        "name": "a65ef206-db3b-4518-a8cc-95a7bc123c81",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Artkode"
      },
      {
        "name": "a4e6c857-7076-4337-a702-83b46fc37ab8",
        "fromTable": "Alle Data",
        "fromColumn": "Avtaleformkode",
        "toTable": "Avtaleform",
        "toColumn": "Avtaleformkode"
      },
      {
        "name": "8988361a-d9e3-4ec5-9e3d-8b7f1dc4d845",
        "fromTable": "Alle Data",
        "fromColumn": "Eieformkode",
        "toTable": "Eieform",
        "toColumn": "Eieformkode"
      },
      {
        "name": "37d74e80-e1be-4590-802b-e88882eab566",
        "fromTable": "Alle Data",
        "fromColumn": "Eierforholdkode",
        "toTable": "Eierforhold",
        "toColumn": "Eierforholdkode"
      },
      {
        "name": "e8ef772c-cf14-492c-8de3-4bb476e2fb0e",
        "fromTable": "Alle Data",
        "fromColumn": "Energitypekode",
        "toTable": "Energitype",
        "toColumn": "Energitypekode"
      },
      {
        "name": "75010ca1-1755-4fd8-9715-87e1026d7f76",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonkode",
        "toTable": "Funksjon",
        "toColumn": "Funksjonkode"
      },
      {
        "name": "68d8d761-4ae7-4af8-be76-1ed421e433b7",
        "fromTable": "Alle Data",
        "fromColumn": "Handsamingstidkode",
        "toTable": "Handsamingstid",
        "toColumn": "Handsamingstidkode"
      },
      {
        "name": "b0af9a5a-8a74-485c-887d-374359492687",
        "fromTable": "Alle Data",
        "fromColumn": "Helsekontrollerkode",
        "toTable": "Helsekontroller",
        "toColumn": "Helsekontrollerkode"
      },
      {
        "name": "b30131bc-5334-4347-b9a0-8cdc43f74444",
        "fromTable": "Alle Data",
        "fromColumn": "Kjønnkode",
        "toTable": "Kjønn",
        "toColumn": "Kjønnkode"
      },
      {
        "name": "3376c024-e11f-4eb3-98f5-f42ab6b3d0ea",
        "fromTable": "Alle Data",
        "fromColumn": "Kildekode",
        "toTable": "Kilde",
        "toColumn": "Kildekode"
      },
      {
        "name": "9031e2d3-8bd2-4e32-b4b7-f80d2ae9b06d",
        "fromTable": "Alle Data",
        "fromColumn": "Kompetansekode",
        "toTable": "Kompetanse",
        "toColumn": "Kompetansekode"
      },
      {
        "name": "5ca7e4c3-bc7d-4919-a513-bc285948e1bc",
        "fromTable": "Alle Data",
        "fromColumn": "Oppholdstidkode",
        "toTable": "Oppholdstid",
        "toColumn": "Oppholdstidkode"
      },
      {
        "name": "ddd6c612-d7e7-4dfd-8e9f-adeeb8c1d433",
        "fromTable": "Alle Data",
        "fromColumn": "Regnskapsbegrepkode",
        "toTable": "Regnskapsbegrep",
        "toColumn": "Regnskapsbegrepkode"
      },
      {
        "name": "51adca4a-e063-4d2f-8e83-97a2259886a1",
        "fromTable": "Alle Data",
        "fromColumn": "Stillingstypekode",
        "toTable": "Stillingstype",
        "toColumn": "Stillingstypekode"
      },
      {
        "name": "5d23b882-fdc3-4fc0-a7c5-185eb9b19b03",
        "fromTable": "Alle Data",
        "fromColumn": "Tiltakskategorikode",
        "toTable": "Tiltakskategori",
        "toColumn": "Tiltakskategorikode"
      },
      {
        "name": "90eab53d-7106-4aad-b6d0-e11c5ed861e7",
        "fromTable": "Alle Data",
        "fromColumn": "Tjenestegrupperkode",
        "toTable": "Tjenestegrupper",
        "toColumn": "Tjenestegrupperkode"
      },
      {
        "name": "6ce6e0ca-f3d0-489b-8fe6-d085362ff862",
        "fromTable": "Alle Data",
        "fromColumn": "Tjenesteområdekode",
        "toTable": "Tjenesteområde",
        "toColumn": "Tjenesteområdekode"
      },
      {
        "name": "66ed20a0-fcd6-49eb-9268-fabb0ef6eda4",
        "fromTable": "Alle Data",
        "fromColumn": "Utdanningkode",
        "toTable": "Utdanning",
        "toColumn": "Utdanningkode"
      },
      {
        "name": "a720969d-8bc6-49a7-8e81-c65838aa4fc7",
        "fromTable": "Alle Data",
        "fromColumn": "Årstrinnkode",
        "toTable": "Årstrinn",
        "toColumn": "Årstrinnkode"
      },
      {
        "name": "6a0b369c-06ec-43eb-9a14-09e35742c3a1",
        "fromTable": "Alle Data",
        "fromColumn": "Nettverkkode",
        "toTable": "Nettverk",
        "toColumn": "Nettverkkode"
      },
      {
        "name": "fffe20ba-31bd-416d-bd61-c268f30b7aa0",
        "fromTable": "Alle Data",
        "fromColumn": "Lærerkompetansekode",
        "toTable": "Lærerkompetanse",
        "toColumn": "Lærerkompetansekode"
      },
      {
        "name": "e93c2126-b5fc-4246-b517-1d3e8d5fd7cc",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "7d2da773-d756-403e-b569-1ad00b2f5e9f",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "565ea40f-5de4-4f49-ade8-e6f70f437e95",
        "fromTable": "Alle Data",
        "fromColumn": "Personellets utdanningkode",
        "toTable": "Personellets utdanning",
        "toColumn": "Personellets utdanningkode"
      },
      {
        "name": "f377b327-4e0f-476b-a64d-925869618be6",
        "fromTable": "Alle Data",
        "fromColumn": "Konklusjon på meldingakode",
        "toTable": "Konklusjon på meldinga",
        "toColumn": "Konklusjon på meldingakode"
      },
      {
        "name": "726fa1a1-5ebe-4a06-a6b6-fe217450989f",
        "fromTable": "Alle Data",
        "fromColumn": "Handsamingstid av meldingakode",
        "toTable": "Handsamingstid av meldinga",
        "toColumn": "Handsamingstid av meldingakode"
      },
      {
        "name": "6f624a3b-dfdd-44bd-8802-8051ab63d1d5",
        "fromTable": "Alle Data",
        "fromColumn": "Konklusjon på undersøking avsluttakode",
        "toTable": "Konklusjon på undersøking avslutta",
        "toColumn": "Konklusjon på undersøking avsluttakode"
      },
      {
        "name": "1e767feb-9db1-47ed-926b-7dc07395ec97",
        "fromTable": "Alle Data",
        "fromColumn": " omsorgs-/hjelpetiltakkode",
        "toTable": "Omsorgs-hjelpetiltak",
        "toColumn": " omsorgs-/hjelpetiltakkode"
      },
      {
        "name": "b1a05385-9d64-48ea-b3b6-14c1e4211038",
        "fromTable": "Alle Data",
        "fromColumn": "Stillingkode",
        "toTable": "Stilling",
        "toColumn": "Stillingkode"
      },
      {
        "name": "523d7fcd-9571-4ced-b1aa-c4b1fc43b889",
        "fromTable": "Alle Data",
        "fromColumn": "Postkode",
        "toTable": "Post",
        "toColumn": "Postkode"
      }
    ],
    "roles": [
      {
        "name": "API",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      },
      {
        "name": "Brukere",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "I04\\VK.DB.VK-SXD0E-002_ASSS.DBO",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1033621"
          }
        ]
      },
      {
        "name": "PowerBI",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "I04\\vk-PowerBIService",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1042837"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}