{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "name": "KS-SQL2018;Reporting_ASSS",
        "connectionString": "Provider=SQLNCLI11;Data Source=KS-SQL2018;Integrated Security=SSPI;Persist Security Info=false;Initial Catalog=Reporting_ASSS",
        "impersonationMode": "impersonateAccount",
        "account": "KSINT\\8093AHA",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Variabelgruppe",
            "dataType": "string",
            "sourceColumn": "Variabelgruppe",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Variabel",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Variabel].* FROM [dbo].[Variabel] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Variabel"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Art",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Art].* FROM [dbo].[Art] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Art].* FROM [dbo].[Art] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Art"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "ASSS Indikatorer",
        "isHidden": true,
        "columns": [
          {
            "name": "Barnehage",
            "dataType": "int64",
            "sourceColumn": "Barnehage",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Miljøforvaltning",
            "dataType": "int64",
            "sourceColumn": "Miljøforvaltning",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Samferdsel",
            "dataType": "int64",
            "sourceColumn": "Samferdsel",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Barnevern",
            "dataType": "int64",
            "sourceColumn": "Barnevern"
          }
        ],
        "partitions": [
          {
            "name": "ASSS Indikatorer",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>113</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>149</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnehage</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Miljøforvaltning</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Samferdsel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Barnevern</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "SFS Kommunale veier i km per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "",
              "var lengde_komvei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "var innb = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "return (",
              "    DIVIDE(lengde_komvei, DIVIDE(innb, 10000)) ",
              ")",
              ""
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Antall km tilrettelagt for syklende som kommunen har ansvaret for per 10 000 innbyggere",
            "expression": [
              "",
              "",
              "var lengde_syklende = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde  tilrettelagt for syklende som kommunen har ansvaret for (km)\")",
              ")",
              "",
              "var innb_ant = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Innbyggere (antall)\")",
              ")",
              "",
              "return (",
              "    DIVIDE(lengde_syklende, DIVIDE(innb_ant, 10000))",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Brutto driftsutgifter eksklusiv avskrivninger samferdsel per km (kroner)",
            "expression": [
              " ",
              "",
              "var agd10 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"332\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ")   ",
              "",
              "var a590 = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),  ",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"12367\"),",
              "    FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"A590\"),",
              "    FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"332\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              ") ",
              "",
              "var vei = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"11814\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lengde kommunalvei (km)\")",
              ")",
              "",
              "Return (",
              "    DIVIDE(",
              "        (agd10 - a590) * 1000, ",
              "        vei",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnader til gatebelysning per lyspunkt, kommunale veier",
            "expression": [
              "",
              "var gate = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"12183\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Brutto driftsutgifter til gatebelysning langs kommunale veier og gater (1000 kr)\")",
              ")   ",
              "",
              "var lys = ",
              "CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "    FILTER(ALL('Tabeller'[Tabellnummer]), [Tabellnummer] = \"11845\"),",
              "    FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lyspunkt langs kommunale veier og gater (antall)\")   ",
              ")  ",
              "",
              "RETURN (",
              "    ROUND(",
              "        DIVIDE((gate * 1000), lys),",
              "        2  ",
              "    )",
              ")"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Drenering/overvann, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til drenering/overvann\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Trafikksikkerhet inkludert skilting og veimerking, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til trafikksikkerhet inkl skilting og vegmerking\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Renhold, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til renhold\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Vinterdrift, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til vinterdrift\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Investeringer til veidekker (asfalt) per meter vei (kroner)",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Investeringer til veidekker\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Sykefravær samferdsel (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "CALCULATE(SUM('Alle Data'[Verdi]),",
              "    FILTER(ALL('Alle Data'[Tabell]), [Tabell] = \"ASSS\"),",
              "    FILTER(ALL('Variabel'[Variabelnavn]), [Variabelnavn] = \"Sykefravær Samferdsel (PAI)\")",
              ")"
            ],
            "isHidden": true,
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Veidekker, kroner per meter vei",
            "expression": [
              "",
              "",
              "var brutto = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Brutto driftsutg eks avskrivninger til veidekker\")",
              ")   ",
              "",
              "var lengde = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"11814\"),",
              "FILTER(ALL(Variabel[Variabelnavn]),Variabel[Variabelnavn] = \"Lengde kommunalvei (km)\")   ",
              ")  ",
              "",
              "Return divide( brutto,(lengde*1000))"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel adkomst- og GS-vei på og/eller over akseptabel standard - tilstandsgrad TG2 (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Andel adkomst- og GS-veg over akseptabelt nivå > TG2\")",
              ")",
              "",
              "return a"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Andel gate og samlevei på og/eller over akseptabel standard - tilstandsgrad TG1 (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Andel gate og samleveg over akseptabelt nivå > TG1\")",
              ")",
              "",
              "return a"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "SFS Kostnad per meter vei for å komme over akseptabel standard (kroner)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"SFS01\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] ",
              "= \"Kostnad per meter veg for å komme over akseptabel standard\")",
              ")",
              "",
              "return a"
            ],
            "displayFolder": "Samferdsel"
          },
          {
            "name": "Netto driftsutgifter barnevernstjenester per innbygger 0-17 år (kroner)",
            "expression": [
              "",
              "",
              "var ndrbv = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "filter(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "filter(all('Funksjon'[Dimensjonskode]), [Dimensjonskode] in {\"244\", \"251\", \"252\"}),",
              "filter(ALL('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Beløp (1000 kr)\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return (DIVIDE((ndrbv*1000),barn))"
            ]
          },
          {
            "name": "Andel barn med undersøkelser i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Barn med undersøking  (antall)\"),",
              "(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100"
            ]
          },
          {
            "name": "Andel barn med barneverntiltak i forhold til innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "DIVIDE(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\"),",
              "(CALCULATE(sum('Alle Data'[Verdi]),Variabel[Variabelnavn]=\"Personer (antall) 0-17 år\")))*100"
            ]
          },
          {
            "name": "Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)",
            "expression": [
              "",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))"
            ]
          },
          {
            "name": "Andel barn som er plassert i løpet av året i prosent av antall barn 0-17 år",
            "expression": [
              "",
              "",
              "var barn017 = CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return DIVIDE([Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)],barn017)*100"
            ]
          },
          {
            "name": "Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)",
            "expression": [
              "",
              "CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Funksjon'[Dimensjonskode]),'Funksjon'[Dimensjonskode] = \"251\"),",
              "FILTER(ALL(Variabel[Variabelnavn]), ",
              "Variabel[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året  (antall) 0-22 år\"))"
            ]
          },
          {
            "name": "Andel barn som ikke er plassert i løpet av året i prosent av alle i tiltak  (0-22 år)",
            "expression": [
              "",
              "",
              "var tiltak022 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all(Variabel[Variabelnavn]), ",
              "'Variabel'[Variabelnavn] = \"Barn med barnevernstiltak i løpet av året (antall) 0-22 år Tiltak i alt\")",
              ")",
              "",
              "return DIVIDE([Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)],tiltak022)*100"
            ]
          },
          {
            "name": "Brutto driftsutgifter per barn (f251) som ikke er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"251\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return DIVIDE((brbv*1000),[Barn med barnevernstiltak i løpet av året 0-22 år som ikke er plassert f251 (antall)])"
            ]
          },
          {
            "name": "Brutto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD10\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000), [Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])"
            ]
          },
          {
            "name": "Brutto driftsutgifter per barn (f244) med undersøkelse eller tiltak (kroner)*",
            "expression": [
              "",
              "",
              "var br244 = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12279\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Brutto driftsutgifter (funksjon 244) per barn med undersøking eller tiltak (kr)\")",
              ")",
              "",
              "return br244"
            ]
          },
          {
            "name": "Andel undersøkelser gjennomført i løpet av 3 måneder (prosent)*",
            "expression": [
              "",
              "",
              "var und= CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12280\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Undersøkingar med handsamingstid innan 3 månader (prosent)\")",
              ")",
              "",
              "return und"
            ]
          },
          {
            "name": "Sykefravær barnevern (PAI) (prosent)*",
            "expression": [
              "",
              "",
              "var a = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"ASSS\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Sykefravær Barnevern (PAI)\")",
              ")",
              "",
              "return a"
            ]
          },
          {
            "name": "Netto driftsutgifter per barn (f252) som er plassert av barnevernet (kroner)",
            "expression": [
              "",
              "",
              "var brbv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              " )",
              "",
              "return divide((brbv*1000),[Barn med barnevernstiltak i løpet av året 0-22 år som er plassert f252 (antall)])"
            ]
          },
          {
            "name": "Andel av netto driftsutgifter barnevern f244 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto244 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"244\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto244,nettobv))*100",
              ""
            ]
          },
          {
            "name": "Andel av netto driftsutgifter barnevern f251 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto251 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"251\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto251,nettobv))*100",
              ""
            ]
          },
          {
            "name": "Andel av netto driftsutgifter barnevern f252 (prosent)",
            "expression": [
              "",
              "",
              "var nettobv = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"FGK13\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "var netto252 = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12367\"),",
              "FILTER(ALL('Art'[Dimensjonskode]), [Dimensjonskode] = \"AGD2\"),",
              "FILTER(ALL('Funksjon'[Dimensjonskode]), [Dimensjonskode] = \"252\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=\"Beløp (1000 kr)\")",
              ")",
              "",
              "return (divide(netto252,nettobv))*100",
              ""
            ]
          },
          {
            "name": "Andel barn med melding av innbyggere 0-17 år (prosent)",
            "expression": [
              "",
              "",
              "var melding = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12615\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Barn med melding (antall)\")",
              ")",
              "",
              "var barn= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"11805\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Personer (antall) 0-17 år\")",
              ")",
              "",
              "return (divide(melding,barn))*100",
              ""
            ]
          },
          {
            "name": "Antall barn med undersøkelse eller tiltak per årsverk (funksjon 244)*",
            "expression": [
              "",
              "",
              "var barn = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12280\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn] = \"Barn med undersøking eller tiltak per årsverk (funksjon 244) (antall)\")",
              ")",
              "",
              "return barn"
            ]
          },
          {
            "name": "Stillinger med fagutdanning av alle fag- og tiltaksstillinger (prosent)",
            "expression": [
              "",
              "",
              "var fag = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12305\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = \"Stillingar med fagutdanning (årsverk)\")",
              ")",
              "",
              "var stillinger= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12305\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Stillingar knytt til sakshandsaming og tiltak frå barnevernstenesta (funksjon 244 unnateke støttefunksjonar, funksjon 251 og 252)  (årsverk)\")",
              ")",
              "",
              "return (divide(fag,stillinger)*100)",
              ""
            ]
          },
          {
            "name": "Andel meldinger som går til undersøkelser (prosent)",
            "expression": [
              "",
              "",
              "var und = CALCULATE(sum('Alle Data'[Verdi]),",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"12189\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Til undersøkelse Meldinger i alt\")",
              ")",
              "",
              "var meld= CALCULATE(sum('Alle Data'[Verdi]),",
              "FILTER(ALL('Alle Data'[Tabell]),'Alle Data'[Tabell]=\"12189\"),",
              "filter(all(Variabel[Variabelnavn]), Variabel[Variabelnavn] = ",
              "\"Meldingar til barnevernet (antall) Meldinger i alt Meldinger i alt\")",
              ")",
              "",
              "return (divide(und,meld)*100)",
              ""
            ]
          },
          {
            "name": "Brutto driftsutgifter per EM (f252) (kroner)",
            "expression": [
              "",
              "",
              "var brem = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Brutto driftsutgifter funksjon 252 enslige mindreårige (1000 kr)\")",
              ")",
              "var antall = CALCULATE(SUM('Alle Data'[Verdi]),   ",
              "filter(all('Alle Data'[Tabell]), 'Alle Data'[Tabell] = \"BMT\"),",
              "filter(all('Variabel'[Variabelnavn]), 'Variabel'[Variabelnavn]=",
              "\"Antall enslige mindreårige f252\")",
              ")",
              "return divide((brem*1000),antall)"
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[ASSS Indikatorer].* FROM [dbo].[ASSS Indikatorer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "ASSS Indikatorer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>113</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>149</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Barnehage</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Miljøforvaltning</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Samferdsel</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Barnevern</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Energitype",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Energitype",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Energitype].* FROM [dbo].[Energitype] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Energitype"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Dimensjonskode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Dimensjonsnavn",
            "dataType": "string",
            "sourceColumn": "Dimensjonsnavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "DimensjonskodeNavn",
            "dataType": "string",
            "sourceColumn": "DimensjonskodeNavn",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Funksjon",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Funksjon].* FROM [dbo].[Funksjon] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Funksjon"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode",
            "sourceProviderType": "Char"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn",
            "sourceProviderType": "Char"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn",
            "sourceProviderType": "Char"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer",
            "sourceProviderType": "Char"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori",
            "sourceProviderType": "Char"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          }
        ],
        "partitions": [
          {
            "name": "Region",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Region].* FROM [dbo].[Region] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Region].* FROM [dbo].[Region] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Region"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tabellnavn",
            "dataType": "string",
            "sourceColumn": "Tabellnavn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "TabellNummerNavn",
            "dataType": "string",
            "sourceColumn": "TabellNummerNavn",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tabeller",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Tabeller].* FROM [dbo].[Tabeller] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Tabeller"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "År",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[År].* FROM [dbo].[År] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[År].* FROM [dbo].[År] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "År"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Alle Data",
        "isHidden": true,
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell",
            "sourceProviderType": "Char"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel",
            "sourceProviderType": "Char"
          },
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Energitypekode",
            "dataType": "string",
            "sourceColumn": "Energitypekode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Handsamingstidkode",
            "dataType": "string",
            "sourceColumn": "Handsamingstidkode"
          },
          {
            "name": "Konklusjonkode",
            "dataType": "string",
            "sourceColumn": "Konklusjonkode"
          },
          {
            "name": "Tiltakskategorikode",
            "dataType": "string",
            "sourceColumn": "Tiltakskategorikode"
          }
        ],
        "partitions": [
          {
            "name": "Alle Data",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] ",
              "dataSource": "KS-SQL2018;Reporting_ASSS"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>95</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>96</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>56</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>76</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>148</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>186</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tabell</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Variabel</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>År</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Verdi</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Artkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Kode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Energitypekode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Funksjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Handsamingstidkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Konklusjonkode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Tiltakskategorikode</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[Alle Data].* FROM [dbo].[Alle Data] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Alle Data"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>95</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>96</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>56</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>76</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>148</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>186</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Tabell</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Variabel</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>År</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Verdi</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Artkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Kode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Energitypekode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Funksjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Handsamingstidkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Konklusjonkode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Tiltakskategorikode</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4e9f0201-a402-446a-8143-3524dec0a92e",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "e93c2126-b5fc-4246-b517-1d3e8d5fd7cc",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabel"
      },
      {
        "name": "7d2da773-d756-403e-b569-1ad00b2f5e9f",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      },
      {
        "name": "664363a3-aadb-4475-b62b-318ab1c5d07f",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "31871d8a-ff9e-49ed-be90-1776353945e4",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Dimensjonskode"
      },
      {
        "name": "f6c09549-e3e3-4916-ad78-64e528b3bc32",
        "fromTable": "Alle Data",
        "fromColumn": "Energitypekode",
        "toTable": "Energitype",
        "toColumn": "Dimensjonskode"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}